- examples/blink.rs
- layout.ld
- src/lang_items.rs
- src/lib.rs
this let us use the normal `main` function in applications instead of the
`tock_main!` macro.
the blink example has been updated and produces the exact same disassembly as
the old version when compiled in release mode
---
@alevy This is looking very neat. Just a `xargo build` and you get a Tock application. Great work 👍
> implement the `start` lang item

- Cargo.toml
- README.md
Because apparently I lurk #rust-internals now and this was an issue
for some totally independent stuff but we may as well do it right
Following guidance from
https://github.com/brson/rust-api-guidelines#crate-and-its-dependencies-have-a-permissive-license-c-permissive
> fixup license metadata

- src/syscalls.rs
This follows the same rationale and is the same clobber set as used
for the C `yield` implementation. This also removes the unneeded
push/pop of the lr.
---
Not yet tested on HW; that's the next step
> syscalls: mark asm clobbers correctly for yieldk

- Cargo.toml
This PR specifies the version of linked-list-allocator instead of using URL
The following error is generated with version ```0.5.0```
```
error[E0599]: no method named `write` found for type `*mut hole::Hole` in the current scope
--> /home/niklasad1/.cargo/registry/src/github.com-1ecc6299db9ec823/linked_list_allocator-0.5.0/src/hole.rs:29:13
|
29 |         ptr.write(Hole { size: hole_size, next: None, });
|             ^^^^^
error[E0599]: no method named `write` found for type `*mut hole::Hole` in the current scope
--> /home/niklasad1/.cargo/registry/src/github.com-1ecc6299db9ec823/linked_list_allocator-0.5.0/src/hole.rs:286:30
|
286 |                 unsafe { ptr.write(new_hole) };
|                              ^^^^^
error: aborting due to 2 previous errors
error: Could not compile …
```
> linked_list_allocator 0.5.0 breaks backward compatibility 

- examples/ble_scanning.rs
- examples/hardware_test.rs
- examples/hardware_test_server.rs
- examples/ipcclient.rs
- examples/simple_ble.rs
- src/ble_parser.rs
- src/ipc_cs/client.rs
- src/lib.rs
- src/result.rs
- src/shared_memory.rs
- src/simple_ble.rs
- src/syscalls.rs
- src/syscalls_mock.rs
**Overview**
This pull request contains the following changes:
- establish a new allow structure to be able to automatically take away shared resources from the kernel when the shared object goes out of scope.
- change the unsubscribe method to the new "subscribe" interface introduced to the kernel by #746.
- change the ble-driver to use the new subscriptions/allowances
** Remark **
The unsubscribe/unallow-changes break compatibility with older kernel versions.
** Testing **
The automatic hardware tests have been run. Manual tests to test unsubscribe/unallow functionality have been run.
** Todos **
Transition to new callbacks / shared resource handling in libtock is not complete.
> New allow structure, de-allow and de-subscribe features

- .travis.yml
- src/ipc/ble_ess.rs
This PR adds code formatting checking to Travis CI. The output is consistent to what VSCode produces.
Currently, the effect of the checker is only visible on https://travis-ci.org/torfmaster/libtock-rs/branches. Would it be possible that someone of the Tock core team sets up Travis CI for libtock-rs?
> Check correct formatting

- README.md
This PR creates a "quick-start" section to Readme.md. I created this PR to satisfy #2. Currently, the build infrastructure consists of the following elements
- Cargo.toml
- xargo.toml
- the target json
- rust-toolchain
- tockloader
- elf2tbf
- layout.ld
- a short shell-script
Any of these components is subject to constant change and perspectively I expect the following could happen
- xargo will be replaced by built-in functionality of cargo
- elf2tbf will land (as a standalone application) on crates.io
- the shell-script will be replaced by a build.rs
- libtock will go to crates.io
When the way libtock is used has stabilized it would make sense to
- set up a detailled guide how to include libtock into a "new" application
- if this still involves lots of boilerplate code/scripts/git …
> Added a quick-start section to the readme.

- examples/ble_scanning.rs
- examples/button_read.rs
- examples/button_subscribe.rs
- examples/hardware_test.rs
- examples/hardware_test_server.rs
- examples/ipcclient.rs
- examples/ipcserver.rs
- examples/temperature.rs
- examples/timer_subscribe.rs
- src/buttons.rs
- src/callback.rs
- src/ipc_cs/client.rs
- src/ipc_cs/server.rs
- src/simple_ble.rs
- src/syscalls.rs
- src/syscalls_mock.rs
- src/temperature.rs
- src/timer.rs
This PR changes `syscalls::subscribe` to consume `&mut CB` instead of `CB`. For more details see #33.
> Fix subscription part of #33

- src/timer.rs
The latest change d233968 introduced regression in the sleep function because the subscription was dropped to early. Putting the timer into an extra variable prevents this.
Testing:
---
The "blink"-app was used to test this change and it is working properly.
> Bugfix: Extract timer into variable so subscription doesn't get dropped.

- src/callback.rs
- src/console.rs
This PR includes two measures to reduce the number of `unsafe` usages in `libtock-rs`:
- Migrate the console code to the safe subscription and allow (fixed very soon) models
- Do not consider commands as unsafe anymore. IMO this is a reasonable assumption since the command interface is based on numbers only and the kernel architecture forbids that those numbers can be mutated or used as pointers. Given the circumstances, I do not see that a command is `unsafe` in terms of Rust.
By the way, the usages of `unsafe` could be further reduced if we had another system call for read-only access, e.g. AllowRead. Is something like this under consideration and/or would it make sense to open and issue?
PS: This PR depends on #35
> Reduce usages of `unsafe`

- .gitmodules
- examples/ble_scanning.rs
- examples/simple_ble.rs
- src/console.rs
- src/debug.rs
- src/ipc/client.rs
- src/ipc_cs/client.rs
- src/shared_memory.rs
- src/simple_ble.rs
- src/syscalls.rs
- src/syscalls_mock.rs
SharedMemory now holds a mutable reference of ShareableMemory such that the latter cannot move on the stack and invalidate the pointer to the byte array passed to the kernel anymore.
- Migration of all calls of allow_ptr to the safe allow-call
The following tests were run:
- Hardware integration tests
- Ble-Scanning and Advertising
> Change design of SharedMemory

- src/console.rs
- src/debug.rs
This pull request fixes the debug module so that debug information can be printed on the console without being dependent on the Heap. This is useful for development and debugging of non-r9-based heap for example but more generally has shown to be a necessary tool for troubleshooting.
> Better debug info

- README.md
- layout.ld
- run_example.sh
Content of this PR
- Update Tock
- Use elf2tab instead of elf2tbf
- Improve folder structure for converted elf files
- Sync linker scripts
> Use elf2tab

- Cargo.toml
- README.md
- examples/ble_scanning.rs
- examples/simple_ble.rs
- run_example.sh
- run_hardware_test.sh
- run_ipc_example.sh
- src/ble_composer.rs
- src/ble_parser.rs
- src/lib.rs
- src/simple_ble.rs
This pull request implements the generation of ble payload in user land as implemented in tock/tock#855 on kernel side. This closes #50.
Unit tests have been written for the payload composer. The two ble apps have been run successfully.
Using serde-derive and corepack in combination with defect messagepack packages leads to memory corruption (reproducable without a ble context) and eventually kernel panics. However, I find it is desireable to have examples of these standard techniques in libtock-rs.
> Implement creation of ble payload in userland

- src/entry_point.rs
- src/lib.rs
This refactors libtock's entry point to avoid a couple of sources of undefined behavior:
1. The [naked functions RFC](https://github.com/rust-lang/rfcs/blob/master/text/1201-naked-fns.md) mentions that naked functions cannot soundly have anything in them except inline assembly, because the stack is not setup. Further, the existing start point relied a local variable (effective_stack_top) surviving across a stack pointer change, which is not guaranteed (it may have been stored on the stack).
1. The ARM C ABI requires the stack pointer to be aligned it a multiple of 8 bytes; the existing stack pointer calculation does not ensure that.
The new entry point is split into two procedures. _start is now almost purely inline assembly and is kept simple, and the Rust code (which will do more …
> Entry point cleanup

- src/lib.rs
- src/unwind_symbols.rs
These symbols should be part of libunwind, which we do not have in Tock. LLVM relies on their existence and inserts references to them even with `panic = "unwind"`. This leads to linker errors similar to `undefined symbol: __aeabi_unwind_cpp_pr0`. This adds dummy definitions of the symbols to prevent the linker errors.
I did some searching, but could not find any other fix to the problem. This seems to be the accepted fix. This was discussed at https://groups.google.com/forum/#!topic/tock-dev/eov8fJmskLk.
> Unwind symbols

- src/entry_point.rs
This commit creates access faults in most of the examples. Thus we have to revert it until we have found the root cause.
> Revert "Initialize .data and .bss in libtock-rs."

- .cargo/config
- layout.ld
- nrf52_layout.ld
- run_example.sh
- src/entry_point.rs
Note: this is a `google`-branch version of #64.
Because ROPI-RWPI support in the compiler is incomplete, this changes the libtock-rs layout file to allow Rust apps to be statically-linked. With this change in place, all language features should work correctly.
The caveat is we lose the ability to dynamically load Tock applications and we need to predict the size of the TBF headers in the application image. When compiler support for ROPI-RWPI is complete I'll implement any necessary dynamic relocation steps and reverse this change.
This change depends on [Initialize .data and .bss in libtock-rs](https://github.com/tock/libtock-rs/pull/63). and [Implement a --protected-region-size... in elf2tab](https://github.com/tock/elf2tab/pull/6).
> [google] Implement static linking

- .cargo/config
- README.md
- layout.ld
- nrf52_layout.ld
- run_example.sh
- src/entry_point.rs
Because ROPI-RWPI support in the compiler is incomplete, this changes the libtock-rs layout file to allow Rust apps to be statically-linked. With this change in place, all language features should work correctly.
The caveat is we lose the ability to dynamically load Tock applications and we need to predict the size of the TBF headers in the application image. When compiler support for ROPI-RWPI is complete I'll implement any necessary dynamic relocation steps and reverse this change.
This change depends on [Initialize .data and .bss in libtock-rs](https://github.com/tock/libtock-rs/pull/63). and [Implement a --protected-region-size... in elf2tab](https://github.com/tock/elf2tab/pull/6).
> Implement static linking

- layout.ld
- nrf52_layout.ld
`.text` is used to specify [section names](https://sourceware.org/binutils/docs/ld/Output-Section-Name.html#Output-Section-Name). In order to specify [memory region](https://sourceware.org/binutils/docs/ld/MEMORY.html) we typically use `ram`,`rom`, `FLASH` etc.,
I picked `FLASH` because that is what is used in `libtock-c`.
The use of `TEXT` for memory region initially confused me when I was trying to understand the new rust static build entry point code.
> Rename `TEXT` memory region to `FLASH`

- examples/hardware_test.rs
- run_hardware_test.sh
In this PR I create some more test cases. The tests need a device connected and the pins 0/1 connected. On the NRF52-DK these pins correspond to the pins p0.03 and p0.04 respectively.
The following features of the library are tested:
- Heap
- Trait objects
- GPIO
- Callbacks
- shared buffers (indirectly via the console)
This gives a possibility to check whether PR cause regression quickly. More precisely it checks following functions of the library: 
- command-syscalls
- allow-syscalls
- allocation of memory
- the entry point
- correct linkage and relocation
> Create hardware test cases

- Cargo.toml
- examples/ble_scanning.rs
- examples/blink.rs
- examples/button_leds.rs
- examples/button_read.rs
- examples/button_subscribe.rs
- examples/gpio.rs
- examples/gpio_read.rs
- examples/hardware_test.rs
- examples/hello.rs
- examples/sensors.rs
- examples/seven_segment.rs
- examples/simple_ble.rs
- examples/temperature.rs
- examples/timer_subscribe.rs
We change the crate name to 'libtock'. From my perspective this makes sense. We have two libraries now:
- libtock (a C library for the tock kernel)
- libtock (a library crate)
This closes: https://github.com/tock/libtock-rs/issues/23.
> Change crate name to libtock.

- .travis.yml
- rustfmt.toml
- src/ble_composer.rs
- src/console.rs
- src/debug.rs
- src/lib.rs
This PR removes the need for heap allocations when printing text to the console. Instead, a stack-based byte buffer is used.
Advantages:
- Stack allocations are cheap and do not lead to memory fragmentation.
- An optionally heapless version of `libtock` could be built in the future.
The PR also contains some minor improvement commits from my stash.
> Do not allocate a new String when printing to the console

- README.md
In this PR I add a short notice to Readme.md to explain how to run the integration tests. Closes https://github.com/tock/libtock-rs/issues/37.
> Update docs: Explain how to run the integration tests.

- src/entry_point.rs
- src/lib.rs
The current allocation strategy has become obsolete with #66. We no longer need the `TockAllocator` wrapper.
> Sane usage of linked list allocator

- README.md
- examples/adc.rs
- examples/adc_buffer.rs
- hail_layout.ld
- run_example.sh
- src/adc.rs
- src/lib.rs
- src/result.rs
- src/sensors/mod.rs
- src/sensors/ninedof.rs
This PR, essentially developed by @flxo, adds ADC support for libtock-rs. Moreover, it proposes new error types for the syscall interface and the particular drivers. Linked by implementing the `From` trait. If accepted we would make this the new standard for all drivers and migrate the remaining drivers in a separate PR.
We could make the examples run on the Hail board and this enables us to fix the sensors drivers, thus beeing able to close https://github.com/tock/libtock-rs/issues/45.
We would be interested in comments concerning the new error types.
The hail support is rudimentary. Switching boards is not ergonomic at the moment and it would be nice if more boards could be supported more easily in the future.
The sample-continuously syscall only samples once. It is not clear whether …
> ADC Support and new Error Types

- README.md
- examples/adc_buffer.rs
- examples/ble_scanning.rs
- examples/simple_ble.rs
- src/ble_composer.rs
- src/ble_parser.rs
- src/shared_memory.rs
- src/simple_ble.rs
In this PR we remove unnecessary usage of variable length vectors. As the BLE payload has a fixed length (39 bytes) we can construct our BLE payload without using the heap.
> Remove unnecessary usage of heap in BLE implememtation.

- hail_layout.ld
- layout.ld
- nrf52_layout.ld
- src/entry_point.rs
- Remove `STACK_SIZE` from `.data` section (as its generating improper relocations) and introduce a seperate `.stack` section.
- Tell the linker that in `FLASH` region, `.data` section is starting at `_etext`.
- In `.crt0_header` section, indicate the correct address for data symbols in flash.
- Document dependency of `STACK_SIZE` with `elf2tab`'s `--stack` option
- Added documentation and renamed variables to be consistent with `libtock-c` and kernel code.
- Moved debug support and initial `app_heap_break` setup to `_start`.
- Fixed `.data` relocation and corrected the parameters to `ALLOCATOR.lock().init(...)`
- Fixed issue #82
> Refactor `layout.ld` and `entry_point.rs`

- Cargo.toml
The latest version of serde requires a newer toolchain. This change allows the examples to keep building, un-breaking the Travis build.
> Pin serde to a specific version, to keep compatibility with libtock-rs' toolchain.

- Cargo.toml
- src/result.rs
For Google's h1b_tests application, this saves 9440 bytes in .text. The caveat is that invoking Debug on a TockValue will not format the value contained in the TockValue::Expected().
This contains the commit from #86 so that Travis passes, and should be merged no sooner than #86 .
> Replace TockValue's auto-derived Debug implementation with a hand-written implementation optimized for size.

- .cargo/config
- riscv32_layout.ld
- src/debug.rs
- src/entry_point.rs
- src/lib.rs
- src/syscalls.rs
Add support for riscv32, this is based on the libtock-c support
https://github.com/tock/libtock-c/commit/33df8f5c87068d153dc8560692258478d3ea749f
> riscv32: Initial support of RISC-V

- examples/panic.rs
- src/lib.rs
This also required to add a dummy structure in libtock, to make sure that the panic_handler is imported.
> Add panic example app, to test the effects of userspace panics.

- src/entry_point.rs
- src/lib.rs
- src/memop.rs
- src/syscalls_mock.rs
This change adds a `memop` module with functions abstracting sub-syscall numbers of `syscall::memop`. The other syscalls already have safe abstractions for each driver, and `memop` functions can be useful for the entry_point and for debugging from userspace.
> Add a memop module defining safe abstractions over syscall::memop.

- Cargo.toml
- riscv32_layout.ld
- src/entry_point.rs
- src/syscalls.rs
This PR contains four things:
1. Fixes the RV32 linker address
2. Updates the linked_list_allocator version to the latest release
3. Hardcode the syscall registers for RV32 ecalls
4. Fix the arguments for RISC-V 32 when calling rust_start
> Miscellaneous fixes

- src/debug.rs
- src/debug/low_level_debug.rs
- src/debug/mod.rs
- src/entry_point.rs
- src/lang_items.rs
- src/syscalls.rs
- src/syscalls_mock.rs
1. Add methods to access LowLevelDebug's integer-printing functionality.
2. Report the "mismatched location" status code when the location check fails.
3. Report the "application panic" status code in the panic handler.
This change depends on https://github.com/tock/tock/pull/1430. By design, if the LowLevelDebug capsule is not present in the kernel this change is a no-op.
> Give libtock-rs support for the LowLevelDebug capsule.

- .travis.yml
This can generally help detect build failures such as https://github.com/tock/tock/pull/1393#issuecomment-539723255.
> Add OSX target for Travis-CI.

- .travis.yml
- Cargo.toml
- build_examples.sh
- src/entry_point.rs
- src/lib.rs
Fixes #106 
- The `spin` feature of the `linked_list_allocator` has been disabled, s.t. the allocator does not rely on atomics anymore.
> Support for RISC-V without atomic

- README.md
- nrf52840_layout.ld
- nrf52_layout.ld
- run_example.sh
- run_hardware_test.sh
It looks like the application start address on nRF52 has moved upwards
by 64kB since the library was tested the last time.
> fix nrf52 layout

- codegen/src/lib.rs
- src/led.rs
Currently, the LED interface calls `panic!` (via `unwrap`) if the LED driver crate is not available on the board. This panic-in-panic recurses until the program faults (stack overflow).
This tweak makes the LED interface more robust, treating a board with no LED syscall driver as if it has 0 LEDs.
This also fixes a stale comment from #115.
> Fix src/led.rs so panic!() doesn't infinitely recurse if the LED driver is unavailable.

- .cargo/config
- .travis.yml
- .vscode/settings.json
- codegen/src/lib.rs
- src/ble_composer.rs
- src/lib.rs
- src/result.rs
- src/temperature.rs
This PR
- Fixes `cargo test`
- Enables the `--all-targets` flag for VSCode. This means, examples and tests will be checked on-the-fly.
- Makes travis complain if there are unfixed warnings
> Fix some old toolchain problems

- .travis.yml
- CONTRIBUTING.md
- README.md
- bors.toml
In this PR I add bors integration for the `libtock-rs` repository as in the `tock` repository.
The idea is to
* establish a clear work flow (every approved PR gets merged if it is mergeable)
* manage (potentially conflicting) different PRs
When the PR is approved I will enable the bors app for this repository.
> Add bors integration for libtock-rs

- .travis.yml
- .vscode/settings.json
- README.md
- codegen/src/lib.rs
- examples/adc.rs
- examples/adc_buffer.rs
- examples/button_read.rs
- examples/button_subscribe.rs
- examples/gpio_read.rs
- examples/hardware_test.rs
- examples/hello.rs
- examples/sensors.rs
- examples/simple_ble.rs
- examples/temperature.rs
- examples/timer_subscribe.rs
- src/adc.rs
- src/ble_composer.rs
- src/console.rs
- src/debug/mod.rs
- src/memop.rs
- src/sensors/ninedof.rs
- src/syscalls/mod.rs
- src/syscalls/platform_arm.rs
- src/syscalls/platform_mock.rs
- src/syscalls/platform_riscv32.rs
- src/timer.rs
In this PR I enable clippy in CI and fix some lints. Some soiutions may be a matter of taste. Most significantly I removed some `unsafe` constraints, where I think there is no unsafety.
> Enable clippy and fix lints

- src/entry_point/mod.rs
- src/entry_point/start_item_arm.rs
- src/entry_point/start_item_riscv32.rs
- src/lib.rs
The error message when not enabling the `#![feature(core_intrinsics)]` feature reads
> use of unstable library feature 'core_intrinsics': intrinsics are unlikely to ever be stabilized, instead they should be used through stabilized interfaces in the rest of the standard library
I think we should - unlike other nightly features which will hopefully be stabilized - not use this unless absolutely necessary. I removed the feature in a straightforward way, however. @jrvanwhy is the expert in that matter.
> Remove intrinsics

- src/lib.rs
- src/memop.rs
In this PR I remove the unstable `offset_from` feature which is used to calculate the number of bytes of a slice of bytes in a given range of addresses (the flash region). Clearly, the feature provides a safe and concise way of computing this. However, I find that using a minimal number of unstable/experimental features here has a higher value.
> Remove unstable offset_from feature

- .cargo/config
- opentitan_layout.ld
This fixes https://github.com/tock/libtock-rs/issues/134 and adds support for building OT apps,
> cargo: Add support for building OpenTitan apps

- src/entry_point/start_item_riscv32.rs
- src/syscalls/platform_riscv32.rs
As of right now, asm clobbers of specific registers in Rust only work
with the registers' x-style names, not the a/t/ra names.
Fixes #139.
See rust-lang/rust#60392.
> Change RISC-V register names in clobbers.

- src/leds.rs
- src/syscalls/platform_mock.rs
This PR contains an "event recorder" which enables to write unit tests which invoke syscalls. The idea is to capture all syscalls and record them to assert which syscalls occur. The return value for a syscall can also be set.  
Comments are very welcome. The mock syscall implementation is very crude because it is good enough to cover the only existing test case. Ideas for meaningful tests are very welcome so I can elaborate which infrastructure is needed to create these tests. Ideas would be
* test the set alarm retry mechanism of the alarm implementation
* test non-trivial callbacks (i.e. temperature)
> Create syscall recorder for tests

- layout_generic.ld
This is a special section that RISC-V uses (see the comment in the Tock board linker). Without this change, we potentially miss part of the .bss being zeroed properly.
> Add .sbss section to .bss section

- .cargo/config
- doc/README.md
$ rustup target install riscv32iamc-unknown-none-elf
error: toolchain 'nightly-2019-11-06-x86_64-unknown-linux-gnu' does not contain component 'rust-std' for target 'riscv32iamc-unknown-none-elf'; did you mean 'riscv32imac-unknown-none-elf'?
> Correct name of RISC-V target

- flash.sh
- layout_opentitan.ld
- layout_riscv32.ld
Currently, all of the scripts that run elf2tab are for the ARM boards and
also call tockloader. None of the RISC-V boards use tockloader at the moment
but still need the final tbf binary. Add a simple script to build and then
run elf2tab.
This can certainly be expanded in the future but right now I'm looking for something simple that we can keep in tree to let RISC-V be built easily against master
> Add a script to build for RISC-V

- layout_generic.ld
We need to reserve space for the stack in the linker script but it doesn't
actually get loaded. Mark this section as NOLOAD to account for this.
While everything seems to usually work okay without NOLOAD I ran into
an issue on a newer toolchain where data was not getting loaded in
the correct place because it was offset by the stack size. Better to
be a little cautious.
> Mark stack as NOLOAD

- src/entry_point/start_item_riscv32.rs
Because RISC-V does not currently have full relocation support,
the addresses in the crt0 header are the exact addreses, not
offsets. This means we don't need to offset by the stack top again
to get the app heap start. Adjust the assembly to account for this.
> Use the absolute addresses for calculation in entry assembly

- src/entry_point/mod.rs
The Tock kernel gives a nominal location for userspace to start the
app heap. This currenlty a minimum size of 3072. On a platform such
as the hifive1 which only has 5K of app memory, this ends up wasting
precious memory.
Given the kernel will probably always guess wrong, just use bss_end.
Applications can adjust the heap size as needed if they actually need
more space.
> Use bss_end for the actual start of the app heap

- layout_riscv32.ld
Reduce the size so we don't go over the memory avaliable in the hardware
or QEMU.
> layout_riscv32.ld: Update the SRAM size to be correct 

- Cargo.toml
- src/alloc.rs
- src/lang_items.rs
If we panic we need ot yield to ensure any remaining prints are printed
by the kernel. This helps with debugging.
> lang_items: Yield on a panic

- .travis.yml
Extend the travis script to actually run a libtock-rs app in QEMU.
To do this we have to drop OS X support.
> travis: Run tests as part of travis CI

- .gitignore
- examples-alloc/ble_scanning.rs
- examples-alloc/simple_ble.rs
- src/drivers.rs
- src/simple_ble.rs
In this PR I migrate the ble scanning funtionality from callbacks to `futures::stream::Streams`. 
Only merge after #122 
* I decided to make the `BleScanningDriverScanning::stream_values` method to consume `&self` instead of `&mut self`. While I think this is correct it may lead to unexpected behavior when two parallel Tasks consume this stream, i.e. the events are split between the consumers
* I only implemented infinite streams as the stream of ble events will be either be stopped at runtime (to a point of time predictable at compile time) or continue to produce values forever.
* I removed the possibilty of registering callbacks to the ble driver directly as for me it seemed to be only feasible for trivial business logic.
> Create stream to stream events from ble scanning functionality merge after #122

- build.rs
- codegen/src/lib.rs
- core/Cargo.toml
- core/build.rs
- core/src/entry_point/mod.rs
- tools/flash.sh
There's not a nice simple way to be able to change the app heap size or the kernel heap size without manually changing the build environment. This is a proposal to allow setting these options via the command line environment variables. This matches what we are doing for PLATFORM. I'm open to other approaches as well.
I'd like to be able to do the same for the stack size but that gets trickier as it is set in the linker script. I have some ideas there as well but I figured I would get feedback on this part before going down that road.
> Allow setting of heap sizes via command line

- Makefile
I have lots of issues of running out of stack, let's add a Makefile
option to print stack usage.
> Makefile: Support dumping stack size usage

- core/src/entry_point/mod.rs
- core/src/entry_point/start_item_riscv32.rs
Start the app's head size at the value of app_head_break passed by the
kernel.
This gives us more space to work with which allows us to create large
buffers (such as for passing to/from the HMAC).
It also means we do what the kernel expects us to do
> core/entry_point: Start the heap at app_heap_break

- Makefile
The hifive1 board needs the 'a' atomic operations as well. Install that
target during setup.
Signed-off-by: Dylan Reid <dgreid@chromium.org>
> Makefile: add riscv32imac target in setup

- Cargo.toml
This fixes https://github.com/tock/libtock-rs/issues/171
> 171 enable debug symbols in release build

- codegen/src/lib.rs
This PR removes the now unecessary `extern crate` statement inside the proc macro. The necessity to use this has been removed in 1.42.0 compiler version.
> Remove extern crate statement

- core/src/shared_memory.rs
Currently, `shared_memory::safe_copy` uses `clone_from_slice` to
perform memory copy. `clone_from_slice` iterates over each element of
slice to invoke 'clone_from'. According to [docs of `clone_from_slice`](https://doc.rust-lang.org/std/primitive.slice.html#method.clone_from_slice),
it can be more performant to use `copy_from_slice` instead when copy target implements `Copy`.
Since we're copying a `u8` slice, I thought replacing `clone_from_slice` with `copy_from_slice` would be a helpful change regarding performance.
Thank you for reviewing this PR :)
> Replace 'clone_from_slice' with 'copy_from_slice'

- boards/layout_opentitan.ld
As Tock for OT has gotten larger the SRAM allocated for apps has moved
up in memory. Let's update the linker script to better match what Tock
is allocating.
> boards: opentitan: Update the SRAM layout

- doc/Dependencies.md
This document is required by [Tock's threat model](https://github.com/tock/tock/blob/master/doc/threat_model/Code_Review.md).
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/threat-model-doc/doc/Dependencies.md)
> Add documentation describing `libtock-rs`'s unaudited third-party dependencies.

- .gitignore
- .gitmodules
- .travis.yml
- Cargo.toml
- Makefile
- README.md
- test-runner/src/main.rs
Prior to this PR, there was no easy way to run `libtock_test` in QEMU. It was run as part of the Travis CI checks, but not `make test`. This PR moves that functionality into the Makefile, so that `make test` runs the QEMU tests.
Main changes in this PR:
1. Added a tock submodule pointing to the kernel version the tests are run against. This submodule is used to build Tock kernels for testing.
1. Tweaked the README to clarify that the Tock submodule has its own license (although it matches libtock-rs' license).
1. Added `make setup-qemu`, automatically run as part of `make qemu`, which compiles QEMU in a new `build` directory. This shouldn't touch the host system, although you need QEMU's dependencies for it to succeed.
1. Tweaked `test-runner` to use the QEMU and Tock kernel built by …
> Add the QEMU test invocation to `make test`

- Cargo.toml
- Makefile
- core/examples/empty_main.rs
- tools/print-sizes/Cargo.toml
- tools/print-sizes/src/main.rs
The tool prints the size of .bss, .data, and .text (which currently includes .rodata). I tried to adjust the linker script to separate out .rodata, but unfortunately that caused RISC-V apps to fault. I'll take care of that in a later PR, when I refactor the entry point and layout script.
I intend to develop a GitHub Action similar to tock/tock's that runs print-sizes on incoming PRs and displays the diff relative to the PR's target branch.
> Add a tool that prints information on the sizes of the examples.

- boards/layout_nrf52.ld
- examples-features/libtock_test.rs
In this PR I amend the memory layout for the nrf52dk to match the kernel size of the tock 1.5 release. This breaks compatibility with previous releases and should be merged alongside with #195 .
I also tested the nrf52840 board which is already working with the 1.5 kernel without any changes.
I ran the test suites on both development boards. However, I did no thorough test of compatibility of `libtock-rs` with the new kernel release.
> Amend memory layout for nordic boards to match tock 1.5 release

- Makefile
- boards/layout_nucleo_f429zi.ld
- boards/layout_nucleo_f446re.ld
- tools/flash.sh
This adds the memory layout for building applications for the Nucelo F429zi and F446re boards.
> Added nucleo

- .github/workflows/size-diff.yml
The diff is computed by building the examples with `make examples` both in the PR's target branch and the merge result, and running `diff` on the result.
This is built using GitHub Actions because upstream Tock is moving to GitHub Actions (see https://github.com/tock/tock/pull/1815, and [this core WG discussion](https://github.com/tock/tock/blob/master/doc/wg/core/notes/core-notes-2020-04-24.md#ci-infrastructure-travis-to-github-actions)).
> Add a CI tool that prints a size diff for incoming PRs.

- core/Cargo.toml
- core/src/alloc.rs
- core/src/entry_point/mod.rs
- core/src/lib.rs
This pull request adds a `heap` feature to the core crate of libtock-rs. This allows to configure the core crate to only enable and initialize the `HEAP` variable, while leaving the choice of defining a custom allocator.
Indeed, the `HEAP` is conveniently initialized in the entry point with the app's heap start/size.
An example use case is in OpenSK (see this pull request https://github.com/google/OpenSK/pull/123), where the custom allocator can print some debugging information about allocations & deallocation to the console - while the heap implementation is the same as the default of libtock-rs (i.e. `linked_list_allocator`).
---
An alternative to this feature could be to somehow communicate the app's heap start/size to the `main` function, so that each app can initialize its own …
> Add a heap feature to libtock-rs/core.

- src/ble_composer.rs
- src/ble_parser.rs
Hello :crab: ,
this PR changes invocations of `clone_from_slice()` to `copy_from_slice()`.
`copy_from_slice()` performs memcpy, while `clone_from_slice()` performs an element-wise copy.
(`copy_from_slice()` should generally run faster than `clone_from_slice()`)
The affected call sites all copy `u8` slices, and since `u8` implements `Copy`, it is safe to use `copy_from_slice()`.
Thank you for reviewing this PR :superhero_woman: :superhero_man: :superhero:
> 'copy_from_slice' instead of 'clone_from_slice' when copying 'u8' slices

- core/src/entry_point/mod.rs
This PR updates the code for zeroing the .bss section.
The updated version uses `core::ptr::write_bytes()` which invokes a single **memset**,
compared to the current code which initializes one byte at a time.
The updated version would initialize the .bss section faster than the current version. 
Thank you for reviewing this PR :) :bowing_man:
> faster zeroing of .bss

- layout_generic.ld
This allows elf2tab to determine what the start of RAM address is when generating a fixed address header in the TBF.
See https://github.com/tock/elf2tab/pull/23 and https://github.com/tock/tock/pull/1845.
> linker: add sram origin symbol

- .travis.yml
- Makefile
- boards/layout_opentitan.ld
Update the OpenTitan SRAM address to make current master Tock, also
update the submodule to use the latest Tock SHA.
> boards: opentitan: Update the OpenTitan SRAM address

- Makefile
PR #207 updated the `tock` submodule. The new submodule version includes the following PR: https://github.com/tock/tock/pull/1880, which changed the `tock` Makefile actions related to QEMU setup. This updates `make setup-qemu` to work with the new Tock makefile.
Tock no longer checks if QEMU was already setup when running setup actions, so I removed `test-qemu-hifive`'s dependency on `qemu-setup`. `make setup` still depends on `qemu-setup`.
> Adjust the setup-qemu and test-qemu-hifive make actions to work with the new tock version.

- CONTRIBUTING.md
- doc/CodeReview.md
The code review policy clarifies:
1. Who "owns" libtock-rs code (who reviews PRs)
1. Who is responsible for merging PRs.
1. When a PR may be merged.
This is based on Tock's policy that is currently at https://github.com/tock/tock/blob/master/doc/CodeReview.md
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/code-review/doc/CodeReview.md)
> Add a code review policy

- Cargo.toml
- Makefile
- core/Cargo.toml
- core/platform/Cargo.toml
- core/platform/src/lib.rs
Currently, the crate is just a skeleton. I will add functionality in future PRs (I am merging an empty crate so that I can send PRs in parallel in the future).
I will be replacing the system call layer in libtock_core::syscalls with a new layer in libtock_platform. libtock_core depends on libtock_platform and will re-export its functionality. This work is tracked at https://github.com/tock/libtock-rs/issues/217
> Add the `libtock_platform` crate.

- .github/workflows/artifacts.yml
- test_runner/src/main.rs
- tools/flash.sh
This PR builds libtock-rs binaries as part of the CI.
The idea here is then other repos (like the Tock kernel) can then use the binaries for testing.
> .github: Build artifacts as part of workflow

- Cargo.toml
- Makefile
- examples-features/libtock_test.rs
1. Update the `tock` submodule to a version that includes
https://github.com/tock/tock/pull/2024, which fixes the OpenTitan BootROM
download code, as well as https://github.com/tock/tock/pull/2038, which fixes
a HiFive1 kernel bug.
2. Disable the callback test. HiFive1 doesn't have a working timer driver. The
callback test only worked before because of some other callback, which
doesn't seem to occur with the new kernel.
Fixes #225
> Fix the broken Travis CI:

- core/platform/src/error_code.rs
- core/platform/src/lib.rs
ErrorCode is a wrapper around an isize that is useful for type safety. Its intended use case is to wrap a non-successful ReturnCode returned from a system call.
> Add the ErrorCode type to libtock_platform.

- .github/workflows/ci.yml
Like the existing Travis CI, this will run `make test` on each new PR. The main tock repository has already switched from Travis to GitHub Actions for better performance and support. Travis currently takes over 30 minutes for each PR, and based on my testing this action usually takes 13-16 minutes. This will help PR authors recognize and fix issues faster.
I plan to run this action concurrently with Travis for a short time to verify it is working, switch bors over to checking this action rather than Travis, then remove the Travis config.
> Add a Continuous Integration GitHub Action.

- core/platform/src/lib.rs
- core/platform/src/syscalls.rs
`Syscalls` is a trait representing Tock's system call API. It will be implemented by both `libtock_runtime` (included by TBF binaries) and `libtock_fake` (included by unit tests). It will allow us to replace the real Tock kernel with a fake Tock kernel for testing purposes.
`Syscalls` is designed to introduce no overhead over the system call assembly logic. For `allow`, `command`, and `subscribe`, it is based on Tock's `Driver` trait. A higher-level interface over Tock's system calls, for use by `libtock_core` and client code, will be introduced in a later PR.
> Add the `Syscalls` trait to `libtock_platform`.

- .github/workflows/artifacts.yml
In the current setup, every time I push any branch to my fork I get an artifacts action run, which seems very wasteful. This change makes the actions workflow only run when master is modified. Note that the workflow will still run in forks, but only when the fork's master branch is updated.
@alistair23 , is this a desirable change?
> Set the artifacts workflow to only run when `master` is pushed to.

- Makefile
- boards/layout_msp432.ld
- tools/flash.sh
Since around two weeks the tock-kernel supports the MSP432 platform, so this PR adds MSP432-support for the userspace.
I only adopted the flash-script and the makefile and added a linker-script for the board.
Flashing apps is currently only possible with openOCD, the makefile in the kernel provides a target to do this.
> MSP432 platform support

- core/platform/src/allows/allowed.rs
- core/platform/src/allows/allowed_tests.rs
When I originally implemented `Allowed`, I made it work with non-`Copy` types. `Allowed::get` cannot with with non-`Copy` types, so I added `Allowed::replace` to allow client code to read a non-`Copy` type out of an `Allowed` buffer. However, during the PR review we changed `Allowed` to only contain `Copy` types. Because of this change, I don't anticipate `Allowed::replace` (and `Allowed::take` which is built on top of `Allowed::replace`) seeing much use. This PR removes `Allowed::replace` and `Allowed::take` to reduce the amount of `unsafe` in `libtock_platform`.
> Remove `Allowed::replace` and `Allowed::take`.

- examples/ctap.rs
- src/ctap.rs
- src/drivers.rs
- src/lib.rs
This adds support for the CTAP driver to libtock-rs. It also adds a very simple example that can use that driver.
This does not yet implement CTAP functionality. Full CTAP needs a lot more features, such as CBOR decoding and then CTAP decoding. This requires some external dependencies to get these features (to avoid re-implementing a CBOR decoder in libtock-rs).
Full CTAP support will be added later, for now this is enough to test the driver and expose basic functionality to interested users and developers.
> ctap: Add initial support for the CTAP driver

- examples-features/alloc_error.rs
- examples-features/libtock_test.rs
- examples-features/panic.rs
- examples/adc.rs
- examples/adc_buffer.rs
- examples/button_read.rs
- examples/button_subscribe.rs
- examples/ctap.rs
- examples/gpio_read.rs
- examples/hello_world.rs
- examples/hmac.rs
- examples/sensors.rs
- examples/temperature.rs
- examples/timer.rs
- examples/timer_subscribe.rs
- src/console.rs
- src/debug/mod.rs
Currently we have a cluncky way of printing by calling the following:
writeln!(console, "My message")?;
Although this works, it means we need to keep track of the console
struct. This makes it difficult to support printing in third party
libraries. This also means that we don't follow the Rust convention of
supporting `print!` and `println!` macros.
This patch makes the console object a global static so that we can
support the `print!` and `println!` macros. All current users are converted
to use this new method.
> console: Add support for println! and print!

- .github/workflows/ci.yml
- .github/workflows/size-diff.yml
- bors.toml
The GitHub Actions workflows work better than Travis, and are a superset of the Travis checks. Travis is currently broken and I'd rather replace it with Actions than fix it. This PR should make Bors listen to GitHub actions rather than Travis.
If this works, then I'll remove the Travis config entirely in a future PR.
> Configure Bors to use GitHub Actions rather than Travis checks.

- examples-features/libtock_test.rs
- layout_generic.ld
RISC-V has the `.sdata` section, which is supposed to be for commonly-accessed global variables. Previously, we discarded this section in the linker script. Discarding this section resulted in missing global variables.
I originally discovered this when I tried to print a string of less than 9 bytes and it was not working. I reported it as a kernel bug at https://github.com/tock/tock/issues/2132, then later realized the issue was in the libtock-rs linker script rather than the kernel.
I added a test to libtock_test that catches this issue (I verified by hand that the test fails if I don't fix the linker script).
> Add the .sdata section to the app binary.

- Cargo.toml
- examples-features/ctap.rs
This PR adds a fully featured CTAP example.
In order to do this we use a few external crates:
* ctap2-authenticator: This handles CBOR decoding (using serde_cbor) and  parses the CTAP data
* p256, subtle and generic-array: Are used for Elliptic Curve crypto
A few remaining issues:
* ~~Platforms without atomics don't work. ~~There are patches sent to the upstream projects, we just need them to update and then the crates we use to update.~~ Just waiting on the next release (0.4.11+) of https://github.com/rust-lang/log/releases~~
* ~~One change for ctap2-authenticator is required, I'll send a patch soon.~~
* The nonce is static. This is not cryptographically sound. This needs to be updated to use Tocks TRNG HIL
* Some functionality is still unimplemented
* ~~`self.hmac.init_driver().unwrap` …
> examples-features: Add a featured CTAP example

- src/sensors/ninedof.rs
Adds `read_gyroscope` to ninedof.
> Add gyroscope read functionality to NinedofDriver

- doc/DesignConsiderations.md
This Design Considerations document outlines a number of considerations that affect the design of `libtock_core` which do not impact most Rust projects. It is intended to help onboard new contributors and to remind long-term contributors of constraints that other `libtock_core` clients have.
[Rendered document](https://github.com/jrvanwhy/libtock-rs/blob/design-doc/doc/DesignConsiderations.md)
> Document several factors constraining `libtock_core`'s design.

- test_runner/Cargo.toml
`test_runner` depends on async-std. async-std depends on crossbeam_utils. crossbeam_utils 1.8 does not work with our nightly Rust (due to `const_fn`-related churn). The existing dependency allows Cargo to pull in async-std 1.7, which pulls in crossbeam_utils 1.8 and breaks our build. By limiting async-std's version to <1.7, this prevents crossbeam_utils 1.8 from being pulled in, keeping our build working.
I tried to update our nightly Rust version to fix this, but encountered several issues that will take some time to solve. This fix is intended to last until we update to a newer Rust nightly.
> Block async-std >= 1.7.0 from being pulled in to fix the CI.

- src/drivers.rs
- src/i2c_master.rs
- src/i2c_master_slave.rs
- src/lib.rs
Tock actually has two I2C capsules, this PR adds support for both in libtock-rs.
> I2C: Add support for all of Tock's I2C capsules

- Cargo.toml
- examples/libmctp.rs
- src/drivers.rs
- src/i2c_master.rs
- src/i2c_master_slave.rs
- src/lib.rs
MCTP (Management Component Transport Protocol) is a transport layer that is commonly used for server management. It supports multiple underlying protocols, but in this case we are focued on SMBus.
This adds initial support for a MCTP example in libtock-rs.
> libmctp: Initial support of MCTP support

- doc/PlatformDesignStory.md
"Platform Design Story" justifies the design of `libtock_platform` by showing how to write an efficient `console` driver.
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/platform-story/doc/PlatformDesignStory.md)
> Add the "Platform Design Story" document.

- test_runner/Cargo.toml
- test_runner/src/main.rs
`test_runner` used both `async-std` and `tokio` to implement a timeout on test execution. This brought in a *large* dependency tree. Some of the crates in that dependency tree (e.g. `value-bag`) assume that if you're on nightly Rust, you have an up to date compiler. At the moment, this is breaking `libtock-rs`' CI: `value-bag` does not build with the toolchain `libtock-rs` uses.
I tried to update the compiler, but newer compilers SIGSEGV on `libtock-rs`. Rather than investigating that (which will likely be very time-consuming), I decided to remove `libtock-rs`' dependency on `value-bag`. This required removing `test_runner`'s dependency on both `tokio` and `async-std`.
I replaced the timeout functionality by spawning a second thread that waits for 10 seconds then kills QEMU.
> Remove `test_runner`'s dependence on `async-std` and `tokio`.

- .github/workflows/artifacts.yml
- .github/workflows/ci.yml
- .github/workflows/size-diff.yml
- Makefile
- core/Cargo.toml
- core/src/lang_items.rs
- layout_generic.ld
- rust-toolchain
I had to update `linked_list_allocator` because it is not compatible with the newer compiler (`const_fn` changes). I also silenced a warning on the `start` definition.
> Specify components in `rust-toolchain` and update the toolchain to `nightly-2020-08-20`.

- core/Cargo.toml
- core/platform/src/error_code.rs
- core/platform/src/lib.rs
- core/platform/src/return_type.rs
- core/platform/src/syscalls_impl.rs
`ErrorCode` now wraps a `usize` rather than an `isize`. I chose `usize` to match the corresponding return values in `RawSyscalls`. I made constants for all the known error codes.
I also added the `ReturnType` struct, which wraps a `u32` (matching the return type in `RawSyscalls`) and represents the discriminator field in the sycall return type. This field represents the `Success`/`Success with u32`/`Failure`/`Failure with u32`/... variation in system call return types. Like `ErrorCode`, I created constants for the known `ReturnType` values.
Both `ErrorCode` and `ReturnType` are designed to be future-compatible in case new error codes or return types are added to the system call ABI.
> Convert ErrorCode to Tock 2.0 semantics and add a ReturnType struct.

- .github/workflows/size-diff.yml
size-diff has been painful in 2 cases:
1. If master is broken, it fails on PRs that fix master's build.
2. If the commands required to build the examples change, it breaks. This happened when we changed rust-toolchain to the TOML format, and removed the `rustup target add` commands from the size-diff workflow. This change was fine once it hit master but broke in the PR.
size-diff still fails if the PR's build fails, so we can still detect PRs that break size-diff's functionality.
> Make size-diff pass if building master fails.

- core/platform/src/raw_syscalls.rs
- core/runtime/src/lib.rs
- core/runtime/src/syscalls_impl_riscv.rs
This introduces `TockSyscalls`, which implements `libtock_platform::RawSyscalls`. The blanket impl of `libtock_platform::Syscalls` in `libtock_platform` gives `TockSyscalls` a `Syscalls` implementation. I will implement ARM system calls in a future PR.
> Implement system calls on RISC-V in libtock_runtime.

- .cargo/config
- .github/workflows/ci.yml
This keep's CI's behavior where it errors if libtock-rs has warnings.
This is a second attempt at PR #270. We can't specify `RUSTFLAGS` directly because doing so overrides all `rustflags` configurations in `.cargo/config`. Those `rustflags` configs are important because they configure relocation and set the linker script. Instead, I append the `"deny warnings"` config to `.cargo/config` in CI itself.
I tested this by opening two PRs in my fork: [one to test that this PR still builds](https://github.com/jrvanwhy/libtock-rs/pull/15), and [one to test it fails if a warning is present](https://github.com/jrvanwhy/libtock-rs/pull/13).
I am not terribly happy with this solution (feels really hacky rather than kinda hacky), so any alternative implementation ideas would be appreciated!
> Allow warnings during local development

- core/runtime/asm/start_prototype.rs
- core/runtime/src/start_prototype.rs
This is a Rust version of the entry point. Using it directly is undefined behavior for multiple reasons (Rust assumes the stack is setup and the globals are initialized), but it can be a useful reference while working on a real (assembly) entry point.
**Question for reviewers:** Do you think this belongs in the repository?
> Add `start_prototype`, a tool used for writing entry point assembly.

- .gitmodules
- Makefile
I intend to use this kernel in integration tests for the Tock 2.0 crates. When we are ready to remove Tock 1.x support, I will remove the duplicate submodule.
> Add a tock2 submodule with a tock-2.0-dev kernel.

- doc/PlatformDesignStory.md
[Rendered](https://www.github.com/jrvanwhy/libtock-rs/tree/platform-update/doc/PlatformDesignStory.md)
The rewritten `libtock-rs` no longer exists only in my head, it is working. I am updating the note at the top of the document because I am sharing it with others and need it to be accurate.
I am implementing more tests to make sure the core abstractions (such as `RawSyscalls`) are all sound, and then I will break it into smaller pieces for review. I will write more docs and tests as I send each piece for review.
> Update the status of the Platform Design Story document.

- Cargo.toml
`bitvec` 0.18.5 pulls in `radium` 0.3.0, which does not support platforms without atomics. Pulling in `bitvec` 0.18.4 brings in `radium` 0.4 instead (was there a bug in 0.4?) which restores our build.
> Fix the build by avoiding `bitvec` 0.18.5.

- core/platform/src/command_return_tests.rs
- core/platform/src/lib.rs
- core/runtime/src/lib.rs
- core/runtime/src/syscalls_impl_riscv.rs
- core/src/entry_point/start_item_arm.rs
- core/src/entry_point/start_item_riscv32.rs
- core/src/lib.rs
- layout_generic.ld
- rust-toolchain
- src/ble_composer.rs
- src/debug/mod.rs
- src/sensors/mod.rs
- test_runner/src/main.rs
- tools/print_sizes/src/main.rs
This includes https://github.com/rust-lang/rust/pull/82141, which is needed in order to add ARM support to `libtock_runtime`. It also allows us to use the `unsafe_op_in_unsafe_fn` lint.
I went ahead and turned on `unsafe_op_in_unsafe_fn` for the Tock 2.0 crates, as I will use that setting in upcoming PRs (in addition to warning on one pattern, it also allows you to use `unsafe {}` in `unsafe` functions).
The toolchain update caused a change in the ELF file generation, which caused elf2tab to identify the wrong flash range for the process binary. To solve this, I moved `start` out of `.text` and merged it into `.crt0_header` to form a new `.start` section. I believe the issue has to do with execute bits on the sections, but it was nontrivial to fix in elf2tab.
The remainder of the changes …
> Update the Rust toolchain to 2021-03-25.

- Makefile
- doc/MiriTips.md
[Rendered doc](https://github.com/jrvanwhy/libtock-rs/blob/miri-flags/doc/MiriTips.md)
This runs code under Miri with the `-Zmiri-symbolic-alignment-check` flag, as well as both with and without `-Zmiri-track-raw-pointers`. This identifies a lot of "gray area" behavior -- that may or may not become specified as undefined behavior in the future -- as undefined behavior.
I also added a tip on how to write tests that identify undefined behavior that Miri doesn't catch by default, such as having uninitialized values in local variables. The documentation tip will be used in the `libtock_unittest` crate as well as per-crate unit tests.
> Run Miri with more flag combinations, and add a Miri Tips doc.

- core/platform/src/lib.rs
- core/platform/src/raw_syscalls.rs
- core/platform/src/syscalls.rs
- core/platform/src/syscalls_impl.rs
- core/platform/src/yield_types.rs
- core/runtime/src/lib.rs
- core/runtime/src/syscalls_impl_riscv.rs
1. RawSyscalls now supports Yield's new return value semantics as well as the `yield-no-wait` variant of Yield.
2. RawSyscalls now supports Exit.
3. RawSyscalls is now usable in Miri with the `-Zmiri-track-raw-pointers` flag.
4. RawSyscalls can now be implemented on ARM: previously, `class` was a runtime value, but it needs to be an immediate value on ARM.
5. The explanation for the design of RawSyscalls was completely overhauled. Instead of listing a bunch of "design considerations" with no connection to the final design, it shows how testing and efficiency considerations lead to its design. I hope the new description is more amenable to discussion. The new design should be a bit more future-proof than the previous design as well.
The new features added have been stabilized, and can be …
> Overhaul RawSyscalls to work with ARM, -Zmiri-track-raw-pointers, the revised Yield, and Exit.

- doc/Overview.md
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/overview/doc/Overview.md)
Overview gives a high-level view of the crates in the Tock 2.0 `libtock-rs`. It is intended to be a useful resource for newcomers to this repository.
All of the crates mentioned in this document exist at https://github.com/jrvanwhy/libtock-rs/tree/wip, and I am in the process of cleaning them up (adding tests + docs) and sending PRs to merge them here. I developed these crates in my fork because of a chicken-and-egg problem: all of these crates depend on [the rewritten `RawSyscalls`](https://github.com/tock/libtock-rs/pull/282), but I couldn't be sure my `RawSyscalls` design was correct until these crates were working.
> [RFC] `libtock-rs` crate organization

- Cargo.toml
- unittest/Cargo.toml
- unittest/src/expected_syscall.rs
- unittest/src/kernel/mod.rs
- unittest/src/kernel/raw_syscalls_impl.rs
- unittest/src/kernel/thread_local.rs
- unittest/src/lib.rs
- unittest/src/syscall_log.rs
`libtock_unittest` is needed in order to unit test `libtock-rs` code that makes system calls. This change contains a small fraction of the library, and intended to be followed up with several more changes that add system call implementations.
I made careful use of `// TODO` comments and `#[allow(unused)]` declarations so that I can send several system call implementations for review in parallel without causing massive merge conflicts.
> Add the `libtock_unittest` crate.

- README.md
This PR fixes the build badge to not show an errored build. It never got switched over when we stopped using Travis-CI
> Fix build badge to show github actions status

- doc/Testing.md
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/testing/doc/Testing.md)
`Testing` describes where unit tests and integration tests will be located in the Tock 2.0 `libtock-rs` crates.
> Add a `Testing` document.

- Makefile
- runtime/asm/asm_arm.S
- runtime/asm/start_prototype.rs
- runtime/extern_asm.rs
- runtime/src/lib.rs
- runtime/src/syscalls_impl_arm.rs
This support includes:
1. ARM entry point assembly.
2. Changes to `start_prototype` so it works with the new `RawSyscalls` and on ARM.
3. A new toolchain specification in `extern_asm.rs`. I renamed "target" to "prefix" because on ARM the tool prefix doesn't match the target triple.
4. An ARM implementation of `RawSyscalls` on `TockSyscalls`.
> Add ARM support to `libtock_runtime`.

- .github/workflows/mac-os.yml
Hopefully installing the ARM toolchain will be faster and more reliable than installing the RISC-V toolchain.
While I was editing the file, I changed he `checkout` action version to `v2`, so we should get automatic upgrades (I'm assuming it is relatively stable).
> Switch Mac OS' CI to ARM.

- .github/workflows/mac-os.yml
- Cargo.toml
- Makefile
- libtock2/Cargo.toml
- libtock2/src/lib.rs
`libtock2` is the "one stop shop" for using `libtock-rs`. It is intended to be easy to use and will provide everything needed to create a `libtock-rs` process binary. However, in order to be easy to use, it will not support unit testing, as described in the [Overview](https://github.com/tock/libtock-rs/tree/master/doc/Overview.md) doc.
`make test` contained several commands that tested `libtock_runtime` specifically. I reworked those commands so they test `libtock2` as well. The new structure uses only exclusion lists to select crates, which means they will never miss newly-added crates.
> Add the `libtock2` crate.

- Cargo.toml
- README.md
- ufmt/Cargo.toml
- ufmt/LICENSE-APACHE
- ufmt/LICENSE-MIT
- ufmt/README.md
- ufmt/macros/Cargo.toml
- ufmt/macros/src/lib.rs
- ufmt/src/helpers.rs
- ufmt/src/impls.rs
- ufmt/src/impls/array.rs
- ufmt/src/impls/core.rs
- ufmt/src/impls/ixx.rs
- ufmt/src/impls/nz.rs
- ufmt/src/impls/ptr.rs
- ufmt/src/impls/std.rs
- ufmt/src/impls/tuple.rs
- ufmt/src/impls/uxx.rs
- ufmt/src/lib.rs
- ufmt/src/macros.rs
- ufmt/tests/vs-std-write.rs
- ufmt/utils/Cargo.toml
- ufmt/utils/src/lib.rs
- ufmt/write/Cargo.toml
- ufmt/write/src/lib.rs
This is the first step in implementing the [debug printing plan](https://github.com/tock/libtock-rs/issues/84#issuecomment-810690991) we discussed during a core WG call last month. This brings in the `ufmt` crate (minus testing code that we won't use). This is a temporary fork of `ufmt`: we will eventually either decide to abandon `ufmt` or to restore the maintenance of `ufmt`.
1. Review the first section of [`ufmt/README.md`](https://github.com/jrvanwhy/libtock-rs/tree/vendor-ufmt/ufmt), which describes how the first commit was created.
1. Review the [diff of`README.md`](https://github.com/jrvanwhy/libtock-rs/commit/5163051a2d7fefbe4c9b1c6ba62b79fa07c324e7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), which is part of the first commit.
1. Review the rest of the …
> Vendor `ufmt` into `libtock-rs`

- syscalls_tests/Cargo.toml
- syscalls_tests/src/lib.rs
Although `Syscalls` is implemented in `libtock_platform`, its unit tests cannot live in `libtock_platform`, due to a confusing "multiple copies of crate" issue that I explained in the comments. Instead, I'm putting its tests into a new crate.
This crate is currently called `syscalls_tests` because it contains tests for the `Syscalls` implementation. I'm happy to take other name suggestions -- I'm not super happy with this one, because it's a bit tricky to remember to add both 's'-es to the name. I don't want to do `platform_tests` because that would break tab completion for `platform/` and I think some `libtock_platform` tests belong in `libtock_platform`.
Like `libtock_unittest`, I am using comments so that I can implement the system calls in parallel without causing merge conflicts. I'm …
> Add the `syscalls_tests` crate.

- doc/CodeReview.md
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/author-submit/doc/CodeReview.md)
This change only applies to PRs authored by `libtock-rs` code owners.
To date, we have asked PR reviewers to merge PRs. In practice, this means the PR author writes something like "This PR is ready to merge" when it is ready to merge, and the PR reviewers respond with `bors r+`. I do not believe that a PR reviewer has given a different response. This seems like an unnecessary back-and-forth.
> [RFC] Allow PR authors to merge their own PR.

- .github/workflows/ci.yml
- runtime/extern_asm.rs
Previously, if `libtock_runtime`'s build script was unable to find a toolchain to build its external assembly with, its build would succeed then the process binary would fail to link. This change makes `libtock_runtime`'s build script panic with a useful error message instead.
> Improve `libtock_runtime`'s error handling if it can't find an assembly toolchain.

- platform/src/error_code_tests.rs
- platform/src/lib.rs
The syscalls TRD says an `ErrorCode` can have any value in [1, 1023]. This test uses Miri to confirm that the `ErrorCode` enum is not missing any of these values.
I verified this test works by changing the `1023` to `1024`, which gave the following error:
```
error: Undefined Behavior: type validation failed: encountered 0x0400 at .<enum-tag>, but expected a valid enum tag
--> platform/src/error_code_tests.rs:7:18
|
7 |         unsafe { *(&value as *const u16 as *const crate::ErrorCode) };
|                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed: encountered 0x0400 at .<enum-tag>, but expected a valid enum tag
|
= help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
= help: see …
```
> Add a test that verifies `ErrorCode` includes every possible value.

- doc/CargoFeatures.md
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/features-doc/doc/CargoFeatures.md)
This doc describes the issue we've discovered with using cargo features from a workspace, and discusses an alternative that `libtock-rs` developers can use to avoid it.
It stems from this code review discussion from several weeks ago: https://github.com/tock/libtock-rs/pull/283#discussion_r605765017
> Add a cargo features doc.

- platform/src/command_return.rs
- platform/src/command_return_tests.rs
- platform/src/error_code.rs
- platform/src/return_variant.rs
- unittest/src/command_return.rs
- unittest/src/lib.rs
This makes the following change to `CommandReturn`, which are needed by my implementation of the Command system call and its tests:
1. Implements `Debug`. This is not a replacement for `ufmt`-based debugging, but rather to support unit tests (e.g. `assert_eq!`).
2. Changes the register values from `usize` to `u32`, as `RawSyscalls` no longer returns its registers as `usize`s. I discovered that code that interacts with `CommandReturn` is cleaner if we store `u32`s in `CommandReturn` rather than `Register`s.
3. `new` is now `pub` rather than `pub(crate)`, as `libtock_unittest` needs to create `CommandReturn` values.
4. I added `CommandReturn::raw_values`, which will be used by `libtock_unittest` to transform `CommandReturn`s from fake drivers and expected syscalls into register values for …
> Update `CommandReturn` in preparation for the Command implementation.

- ufmt/src/impls/ixx.rs
- ufmt/src/impls/ptr.rs
- ufmt/src/impls/uxx.rs
- ufmt/src/lib.rs
- ufmt/write/src/lib.rs
According to the current Rust Reference [1], storing an uninitialized `u8` is undefined behavior. This may change in the future [2], but for now we should continue to assume it is undefined behavior.
Every use of `core::mem::uninitialized` in `ufmt` is to create a local `[u8; _]`, and therefore is an example of this undefined behavior. I removed the undefined behavior in the simplest way possible, which is to replace the initializers with `[u8; _]`.
[1] https://doc.rust-lang.org/reference/behavior-considered-undefined.html
[2] https://github.com/rust-lang/unsafe-code-guidelines/issues/77
> Remove uses of `core::mem::uninitialized` from `ufmt`.

- platform/src/yield_types.rs
- unittest/src/expected_syscall.rs
- unittest/src/kernel/mod.rs
- unittest/src/kernel/raw_syscalls_impl.rs
- unittest/src/kernel/yield_impl.rs
- unittest/src/kernel/yield_impl_tests.rs
- unittest/src/syscall_log.rs
This Yield implementation will be used by the unit tests of the `libtock_platform::Syscalls` yield calls. This implementation is currently partial, as the `fake::Driver` trait and upcall queue have not been designed yet.
I also changed `libtock_platform::YieldNoWaitReturn` to use the new upcall terminology rather than callback.
> Implement Yield in `libtock_unittest::fake::Kernel`.

- unittest/src/kernel/mod.rs
- unittest/src/kernel/thread_local.rs
- unittest/src/kernel/yield_impl_tests.rs
Instead of asking each unit test to name its kernel, we can instead use Rust's `#[track_caller]` feature to identify each kernel instance. This reduces the amount of boilerplate used in each unit test, and eliminates the chance of copy+paste resulting in two tests with identically-named kernels.
I will manually deconflict this with my other PRs.
> Remove `fake::Kernel::new`'s `name` argument, use `#[track_caller]` instead.

- platform/src/constants.rs
- platform/src/lib.rs
- platform/src/syscalls_impl.rs
- runtime/asm/start_prototype.rs
- unittest/src/kernel/raw_syscalls_impl.rs
I realized I was developing redundant definitions of system call class IDs and yield operations. `libtock_platform` needs them to implement `Syscalls`, `libtock_unittest` implements them to implement `RawSyscalls`, and `libtock_unittest`'s internal unit tests needs them to invoke `RawSyscalls`.
To try to avoid this duplication, I decided to add the constants to `libtock_platform`, so they would be available to all `libtock-rs` crates.
I will manually de-conflict this PR with my other outstanding PRs before I merge them.
> Move the class ID and yield op constants into a new `constants` module in `libtock_platform`.

- platform/src/async_traits.rs
- platform/src/raw_syscalls.rs
- platform/src/syscalls.rs
- unittest/src/kernel/mod.rs
- unittest/src/kernel/thread_local.rs
Most of these reference tasks that have been completed (e.g. creating the `libtock_unittest` crate). One mentions adding tests; this PR adds those tests and removes the TODO.
I also changed a reference to `libtock_unittest::FakeSyscalls` into `libtock_unittest::fake::Kernel`, as I have renamed the fake kernel.
> Clean up several TODO messages.

- build.rs
The support for the `platform` file broke when `libtock_platform`
was moved into the `platform` directory. If not specifying the
`PLATFORM` environment variable, the build currently breaks, so
it appears that the `platform` file support is not being used.
> Remove support for `platform` file.

- unittest/src/expected_syscall.rs
- unittest/src/kernel/command_impl.rs
- unittest/src/kernel/command_impl_tests.rs
- unittest/src/kernel/mod.rs
- unittest/src/kernel/raw_syscalls_impl.rs
- unittest/src/syscall_log.rs
This Command implementation will be used by the unit tests for `libtock_platform::Syscalls::command()`. This implementation includes support for expected system calls, but not fake drivers. I will add fake driver support in the future.
> Implement Command in `libtock_unittest::fake::Kernel`.

- platform/src/syscalls.rs
- platform/src/syscalls_impl.rs
- syscalls_tests/src/command_tests.rs
- syscalls_tests/src/lib.rs
This adds `command` to the `libtock_platform::Syscalls` trait, as well as its implementation. This PR includes unit tests for Command.
> Implement the Command system call.

- doc/FakeKernelOwnership.md
- unittest/src/driver.rs
- unittest/src/kernel/mod.rs
- unittest/src/lib.rs
I will add individual interfaces (Allow, Command, and Subscribe) in the future, as they all have their own design work to do.
I also added a [document](https://github.com/jrvanwhy/libtock-rs/blob/driver/doc/FakeKernelOwnership.md) explaining why `Rc` is used so extensively, and how we avoid unclear ownership and cyclic references. I'm a bit concerned I'm overusing `Rc` here, but I'm having trouble finding a better design.
> Add the `libtock_unittest::fake::Driver` trait.

- unittest/src/driver.rs
- unittest/src/kernel/command_impl.rs
- unittest/src/kernel/command_impl_tests.rs
- unittest/src/kernel/mod.rs
I made `command` required, because I expect every well-designed driver to support Commands. For Subscribe and Allow calls, I will provide a default implementation, because there are drivers that don't use them (e.g. `LowLevelDebug`).
> Add Command to `fake::Driver`, and invoke it from `fake::Kernel`.

- Makefile
Once `asm!` is stable, we want `libtock-rs` to build on a stable toolchain. Some of `libtock-rs`' crates (particularly `libtock_platform` and `libtock_unittest`) already compile with a stable toolchain. This adds a check to `make test` that verifies those crates compile with a stable toolchain.
> Add a check that some crates build with a stable toolchain.

- platform/src/raw_syscalls.rs
- platform/src/register.rs
- unittest/Cargo.toml
- unittest/src/driver.rs
- unittest/src/kernel/command_impl.rs
- unittest/src/kernel/command_impl_tests.rs
- unittest/src/kernel/mod.rs
- unittest/src/kernel_data.rs
- unittest/src/lib.rs
- unittest/src/upcall.rs
This change adds an upcall queue to the kernel data. I plan to implement the following in separate PRs:
1. Upcall invocation in Yield
2. Subscribe
I added a TODO to write a test for fake::Kernel::add_driver. There are a couple refactorings I want to do to it, and if I write the test now, I'll have to change it significantly when I do those refactorings. Therefore I left the test out of this PR.
> Add an upcall module to `libtock_unittest`.

- .rgignore
I use ripgrep all the time in this repository, and by default it searches the Tock submodules. I almost never want that behavior. This file makes ripgrep skip those paths. It can be overridden with ripgrep's `--no-ignore` flag, although that will ignore `.gitignore` as well.
> Tell ripgrep not to search tock/ and tock2/.

- platform/src/constants.rs
- unittest/src/allow_db.rs
- unittest/src/expected_syscall.rs
- unittest/src/fake/driver.rs
- unittest/src/fake/kernel.rs
- unittest/src/fake/syscalls/allow_ro_impl.rs
- unittest/src/fake/syscalls/allow_ro_impl_tests.rs
- unittest/src/fake/syscalls/mod.rs
- unittest/src/fake/syscalls/raw_syscalls_impl.rs
- unittest/src/fake/syscalls/raw_syscalls_impl_tests.rs
- unittest/src/kernel_data.rs
- unittest/src/syscall_log.rs
This fake Read-Only Allow implementation will be used by unit tests for the Allow API in `libtock_platform::Syscalls` and code built on `Syscalls`.
This is missing some tests I wanted to write because this PR was getting too large. I'll add them in the future.
This PR implements the renaming discussed in #324, and starts the `raw_syscalls_impl_tests.rs` files. There are already some tests (for Yield and Command) that belong in `raw_syscalls_impl_tests.rs`, which I will move in a future PR.
> Implement Read-Only Allow in `libtock_unittest::fake::Kernel`.

- unittest/src/fake/syscalls/yield_impl.rs
- unittest/src/fake/syscalls/yield_impl_tests.rs
- unittest/src/upcall.rs
With this PR, calling the Yield system calls will correctly invoke queued upcalls. This PR and #329 implement the fake Subscribe implementation in `libtock_unittest`.
> `libtock_unittest`: make Yield invoke queued upcalls.

- unittest/src/allow_db.rs
- unittest/src/expected_syscall.rs
- unittest/src/fake/driver.rs
- unittest/src/fake/syscalls/allow_rw_impl.rs
- unittest/src/fake/syscalls/allow_rw_impl_tests.rs
- unittest/src/fake/syscalls/mod.rs
- unittest/src/fake/syscalls/raw_syscalls_impl.rs
- unittest/src/fake/syscalls/raw_syscalls_impl_tests.rs
- unittest/src/syscall_log.rs
Read-Only Allow and Read-Write Allow have very similar implementations, but unfortunately it's not easy to use a single implementation for both. I see the following possibilities:
1. Use a complex new trait with associated constants to combine `allow_ro` and `allow_rw` into a single generic function.
2. Use a single `macro_rules!` macro to implement both.
3. Have two very similar system call implementations.
Ultimately, I feel that option 3 is the most maintainable option, despite the extremely similar code for the two system calls. As a result, this PR is almost an exact copy of #326 but with "read-only" replaced with "read-write".
> Implement Read-Write Allow in `libtock_unittest::fake::Kernel`.

- doc/CodeReview.md
This temporary change in policy will last until the Tock 2.0 crates are ready, and was agreed upon by the Tock core working group today (2021-09-17).
For transparency, lets wait to merge this until the core WG notes from today's meeting have been posted publicly.
> Shorten the PR merge delay while we are working on Tock 2.0 crates.

- Makefile
- core/src/stack_size.rs
- ufmt/src/lib.rs
- unittest/src/exit_test/mod.rs
- unittest/src/exit_test/tests.rs
- unittest/src/fake/syscalls/exit_impl.rs
- unittest/src/fake/syscalls/exit_impl_tests.rs
- unittest/src/fake/syscalls/mod.rs
- unittest/src/fake/syscalls/raw_syscalls_impl.rs
- unittest/src/lib.rs
Calling Exit on a fake kernel will cause the test process to exit.
I wanted to make Exit unwind, but that would make it impossible to test error handling in Allow implementations. In particular, the critical `Drop` implementation in #338 cannot be tested if Exit unwinds, as unwinding past the destructor would immediately cause undefined behavior.
In order to make code that calls Exit testable, I added an `exit_test` function (in the `exit_test` module). `exit_test` spawns a new process to run test code that should exit, and verifies the test code does call Exit.
`exit_test` is not usable under Miri, so I added a non-Miri test invocation to `make test`. This caused two issues:
1. It started executing doc tests, and some of our doc tests are broken. I ignored the doc tests for now.
2. Some …
> Implement Exit in `libtock_unittest`, and add functionality for testing Exit calls.

- examples-features/ble_scanning.rs
- platform/src/command_return_tests.rs
- rust-toolchain
- src/timer.rs
- unittest/src/exit_test/mod.rs
- unittest/src/fake/kernel.rs
This fixes CI. CI broke because `cargo miri test` runs `cargo install xargo`, and the latest `xargo` requires a newer toolchain than we were using.
`cargo miri test` now appears to run doc tests, regardless of whether or not they are marked `#[cfg(not(miri))]`. That caused a test failure when `exit_test` was run. To fix this, I added some manual config annotations into the `exit_test` doc test to make it a no-op under Miri.
Changes in lints led to the following tweaks:
1. A number of `assert_eq!(..., <bool>)` checks were replaced with `assert!(...)`.
2. An unused field was removed from the `ble_scanning` example.
3. A `std::mem::replace` call was migrated to `std::mem::take`.
> Update the Rust toolchain to 2021-05-27.

- platform/src/lib.rs
- platform/src/syscall_scope.rs
`syscall_scope` creates a scope in which Allow and Subscribe system calls can be soundly executed, by guaranteeing that the buffers and upcalls are revoked before their lifetime ends. The exact system calls (type and ID) are inferred from the type of the closure passed to `syscall_scope`, using the `ShareList` trait.
`syscall_scope` is the `run` function described at https://github.com/tock/libtock-rs/issues/341, and `ShareList` is the `SyscallList` trait.
> Add `syscall_scope`, a scope guard for system calls.

- Cargo.toml
- apis/low_level_debug/Cargo.toml
- apis/low_level_debug/src/lib.rs
- apis/low_level_debug/src/tests.rs
- libtock2/Cargo.toml
- libtock2/src/lib.rs
This resolves "Implement a `LowLevelDebug` driver" in #322.
> Implement a userpsace low-level debug API for Tock 2.0

- platform/src/allow_rw.rs
- platform/src/default_config.rs
- platform/src/lib.rs
- platform/src/syscalls.rs
- platform/src/syscalls_impl.rs
- syscalls_tests/src/allow_rw.rs
- syscalls_tests/src/lib.rs
This API and implementation are very similar to the Read-Only Allow API in https://github.com/tock/libtock-rs/pull/348.
> Add a Read-Write Allow API to `libtock_platform`.

- doc/FakeKernelOwnership.md
- syscalls_tests/src/allow_ro.rs
- syscalls_tests/src/allow_rw.rs
- syscalls_tests/src/subscribe_tests.rs
- unittest/src/fake/kernel.rs
- unittest/src/fake/low_level_debug/mod.rs
- unittest/src/fake/low_level_debug/tests.rs
- unittest/src/fake/mod.rs
- unittest/src/fake/syscall_driver.rs
- unittest/src/fake/syscalls/allow_ro_impl.rs
- unittest/src/fake/syscalls/allow_rw_impl.rs
- unittest/src/fake/syscalls/command_impl_tests.rs
- unittest/src/kernel_data.rs
- unittest/src/upcall.rs
https://github.com/tock/tock/pull/2659 renamed the Tock kernel's `Driver` trait to `SyscallDriver`, because the term "driver" has too many different meanings in Tock. This change does the same, but `libtock_unittest`'s fake version of the trait.
> Rename `fake::driver` to `fake::SyscallDriver`.

- Makefile
- runtime/layouts/microbit_v2.ld
- tools/flash.sh
The PR adds the microbit_v2 memory layout and modifies `flash.sh` to (hopefully) work with both versions of libtock.
It also adds the`microbit_v2` board to the Makefile, even tough Makefile uses libtock1.
> Add microbit_v2 layout

- runtime/layouts/esp32-c3-devkitM-1.ld
- tools/flash.sh
This PR adds the layout for the esp32 c3 dev kit m1.
While building works and the application starts, it faults when calling `rust_start` with illegal instruction. Modifying `rust_start` to a single loops seems to fail with `Illegal instruction access` as it seems to pass over the loop.
I am out of ideas on how to debug this further on, as I do not have a debugger for the esp, but I don't think the bug is related to the layout. The command used to build he app is 
```bash
alexandru:ibtock-rs/libtock2$ LIBTOCK_PLATFORM=esp32-c3-devkitM-1 APP_HEAP_SIZE=1024 KERNEL_HEAP_SIZE=1024 cargo run --target riscv32imac-unknown-none-elf --example low_level_debug
```
> Layout for esp32 c3 devkit m1

- Makefile
As discussed at https://github.com/tock/libtock-rs/pull/363, issue #362 is fixed in the latest `elf2tab`. I did not have the latest `elf2tab`, because I used `make setup` to install `elf2tab`.
I traced the version number argument back to #157, and did not see a discussion about the version number, so I think it's safe to remove it.
> Adjust `make setup` to install the latest `elf2tab` release rather than pinning `0.6.0`.

- Cargo.toml
- apis/leds/Cargo.toml
- apis/leds/src/lib.rs
- apis/leds/src/tests.rs
- libtock2/Cargo.toml
- libtock2/examples/leds.rs
- libtock2/src/lib.rs
- unittest/src/fake/leds/mod.rs
- unittest/src/fake/leds/tests.rs
- unittest/src/fake/mod.rs
This PR adds a LEDs driver similar to the `LowLevelDebug` one, but very different from the previous LEDs driver (libtock1).
> Leds driver (v1)

- apis/leds/src/lib.rs
- apis/leds/src/tests.rs
- libtock2/examples/leds.rs
- platform/src/command_return.rs
- platform/src/command_return_tests.rs
- platform/src/error_code.rs
- platform/src/error_code_tests.rs
- platform/src/lib.rs
There are a few changes that this makes:
- `CommandReturn` is `#[must_use]`
- `ErrorCode` includes `BadRVal`
- `CommandReturn` has a `to_result` method
I experimented with a few methods of structuring `to_result` to have the
smallest overhead per monomorphization. What you see here is the best I
could do. I also tried:
- Providing a `try_to_result` and using that (lots of overhead)
- Preserving the error code of the failure variant on `BADRVAL`
- Associated constant `FailureData::BADRVAL`
- Associated fn `FailureData::from_wrong_variant(r1: ErrorCode) -> Self`
- A helper function `fn to_result_helper(self, success_variant: ReturnVariant, error_variant: ReturnVariant) -> (bool, u32, u32, u32)` that would do the branches and replacing `r1` with `BadRVal` and other registers with `0` in the …
> Add a simple way to convert a CommandReturn into a Result

- .cargo/config
- .github/workflows/ci.yml
- Cargo.toml
- Makefile
- runner/Cargo.toml
- runner/src/elf2tab.rs
- runner/src/main.rs
- runner/src/output_processor.rs
- runner/src/qemu.rs
- runner/src/tockloader.rs
This replaces `tools/flash.sh`. In the future, it will have functionality to process test output, and will therefore replace `test_runner` as well.
It can currently deploy to HiFive1 on QEMU, and has untested logic to deploy via `tockloader`.
It is no longer possible to deploy Tock 1.0 libtock-rs apps using `cargo run`, as `cargo run` will now invoke the new tool. This prevents us from running the Tock 1.0 libtock-rs integration test, so I have removed it from `make test`.
I also make the following changes to the submodule setup:
1. I added a `setup-qemu-2` target to build QEMU in the tock2/ submodule. When I remove the `tock/` submodule, I'll also remove the `setup-qemu` target and rename `setup-qemu-2` to `setup-qemu` to replace it.
2. I updated the `tock2/` submodule to a newer kernel. …
> Add a runner for libtock2 examples.

- .ignore
Ripgrep and [tokei](https://github.com/XAMPPRocky/tokei) both support `.ignore` (and presumably other tools as well).
> Rename `.rgignore` to `.ignore` so it works with other tools.

- Makefile
- platform/src/command_return.rs
- platform/src/raw_syscalls.rs
- runtime/src/lib.rs
- runtime/src/syscalls_impl_arm.rs
- runtime/src/syscalls_impl_riscv.rs
- rust-toolchain
`clippy` now requires a `# Safety` comment on `unsafe` traits, which required a few changes. Also, Miri renamed `-Zmiri-track-raw-pointers` to `-Zmiri-tag-raw-pointers`.
> Update the Rust toolchain to `nightly-2022-01-20`.

- platform/src/error_code.rs
The derive(Debug) impl will generate a huge amount of code for all of the unused variants. This bit us today :)
Ideally we only use ufmt, but this will let us use `.unwrap` without inexplicably exploding binary size.
> Use a hand-written ErrorCode Debug impl, not derived

- apis/leds/src/lib.rs
- apis/low_level_debug/src/lib.rs
- apis/low_level_debug/src/tests.rs
- unittest/src/fake/leds/mod.rs
- unittest/src/fake/leds/tests.rs
- unittest/src/fake/low_level_debug/mod.rs
- unittest/src/fake/low_level_debug/tests.rs
This PR renames the `DRIVER_ID` to `DRIVER_NUMBER` to be consistent with the drivers TRD naming.
> Rename DRIVER_ID to DRIVER_NUM

- platform/src/raw_syscalls.rs
- runtime/src/lib.rs
- runtime/src/syscalls_impl_arm.rs
This is a temporary approach, that assumes (perhaps optimistically) that `asm_const` will be stabilized in a reasonable timeframe. If it looks like `asm_const` will not be stabilized for a while, we should redesign `RawSyscalls`.
> Remove our use of `#![feature(asm_const)]`.

- .github/workflows/artifacts.yml
- .github/workflows/ci.yml
- .github/workflows/mac-os.yml
- .github/workflows/size-diff.yml
- runtime/extern_asm.rs
- runtime/src/startup/asm_riscv32.s
- runtime/src/startup/mod.rs
- runtime/src/startup/start_prototype.rs
Building `libtock_runtime` on RISC-V no longer requires an external toolchain! We use `global_asm!` instead.
This runs into a LLVM bug where it fails to parse a comment after a `mv` instruction unless the `mv` instruction has a semicolon after it, so I added a semicolon. I'm not sure where to put a descriptive comment, though.
I have not migrated the ARM entry point to `global_asm!`. When I tried, it generated significantly different code from the external toolchain, and I have no way to test if the new code works. Perhaps it's a Thumb 1 vs. Thumb 2 thing? I'll leave debugging that to someone else.
> Migrate the RISC-V entry point to `global_asm!`.

- ufmt/macros/Cargo.toml
- ufmt/macros/src/lib.rs
- ufmt/src/impls/core.rs
- ufmt/src/impls/ixx.rs
- ufmt/src/impls/std.rs
- ufmt/src/impls/uxx.rs
- ufmt/src/lib.rs
- ufmt/tests/vs-std-write.rs
This change adds ufmt support for hex printing of numbers and for fixed-width printing up to widths of 18 using 0s or spaces
as padding. 0 padding is only supported for numbers. Custom fill characters and specified alignment is not supported. This change does decrease the size savings of ufmt relative to core::fmt, but brings them much closer to feature parity.
This change has not been submitted to the upstream ufmt repo, as it includes variations on several changes already submitted as PRs to that repo which have not been accepted: https://github.com/japaric/ufmt/pull/25 and https://github.com/japaric/ufmt/pull/26 .
A number of tests were added to verify that ufmt formatting is identical to core::fmt formatting for the supported additions. These can be run using `cargo test …
> ufmt: add support for hex printing and width specifiers

- syscalls_tests/src/allow_ro.rs
- syscalls_tests/src/allow_rw.rs
- syscalls_tests/src/subscribe_tests.rs
- unittest/src/expected_syscall.rs
- unittest/src/fake/leds/mod.rs
- unittest/src/fake/low_level_debug/mod.rs
- unittest/src/fake/syscall_driver.rs
- unittest/src/fake/syscalls/allow_ro_impl.rs
- unittest/src/fake/syscalls/allow_ro_impl_tests.rs
- unittest/src/fake/syscalls/allow_rw_impl.rs
- unittest/src/fake/syscalls/allow_rw_impl_tests.rs
- unittest/src/fake/syscalls/exit_impl.rs
- unittest/src/fake/syscalls/raw_syscalls_impl_tests.rs
- unittest/src/fake/syscalls/subscribe_impl.rs
- unittest/src/fake/syscalls/subscribe_impl_tests.rs
- unittest/src/fake/syscalls/yield_impl_tests.rs
- unittest/src/syscall_log.rs
- unittest/src/upcall.rs
As noticed in #373, this repository uses a mix of `_number` and `_num` for allow/command/driver/exit/subscribe numbers. We decided to use `_num` everywhere for consistency. This PR replaces the `_number` suffixes with `_num`.
There are still many uses of `_id` in the code from before TRD104 standardized on using "number" for those values. This PR is already getting large, so I'll leave that for a separate PR.
> Replace `_number` with `_num` for consistency.

- .github/workflows/ci.yml
- Makefile
This does not remove use of the nightly toolchain, because:
1. `cargo miri` requires nightly
2. I intend to use `#![feature(custom_test_frameworks)]` to build an integration test framework.
3. We will need `#![feature(default_alloc_error_handler)]` when we provide a global memory allocator (which will be an optional feature of `libtock-rs`).
> Verify in CI that all `libtock-rs` crates build on stable.

- doc/CodeReview.md
Thank you to @torfmaster and @Woyten for all the work you have put into `libtock-rs`!
> Remove owners who have not contributed in the past year.

- runtime/libtock_layout.ld
- runtime/src/startup/asm_arm.s
This is an alternative fix for the issue that https://github.com/tock/libtock-rs/pull/392 fixes. The underlying issue is that `rust-lld` (based on LLVM's LLD) and GCC's `ld` handle the Thumb bit differently. `rust-lld` sets the Thumb bit for symbol addresses, and `ld` does not, resulting in different `rt_header.start` values.
This PR resolves that issue by clearing the Thumb bit in the linker script when setting `rt_header.start`, and modifying the ARM startup assembly to no longer expect the Thumb bit to be set. Now, `libtock_runtime` should correctly start with either linker. This *should* be a no-op on RISC-V (where `.start` is always aligned to a multiple of 4 address), and was tested by hand on RISC-V using QEMU.
> Clear the Thumb bit on `.start`'s address to be compatible with both `ld` and `lld`.

- doc/CodeReview.md
We put a temporary policy in place to allow the Tock 2.0 libraries to be completed quickly. libtock-rs is usable on Tock 2.0, so this PR removes that policy.
I also redefine "upkeep PR" and "significant PR" in a manner that makes most PRs upkeep PRs. Changing these definitions was discussed on the 2022-02-11 core WG call. The new definitions are intended to align with the impact a PR has on other `libtock-rs` contributors: if a PR is going to conflict with others' work, it should have a merge delay, otherwise it can be merged quickly.
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/new-review-defs/doc/CodeReview.md)
> Code review policy updates

- runtime/src/lib.rs
- runtime/src/startup/mod.rs
With this fix, other crates can use libtock2 without worrying about its deps.
Otherwise, the macro `set_main! {main}` breaks when used from another crate.
Example: https://gitlab.com/dcz_self/seistock
- adjust path to libtock,
- remove contents of the main function and imports (not upstreamed yet),
- run `just build`
> Fix crate resolution inside macro

- Cargo.toml
- apis/console/Cargo.toml
- apis/console/src/lib.rs
- apis/console/src/tests.rs
- libtock2/Cargo.toml
- libtock2/examples/console.rs
- libtock2/src/lib.rs
- unittest/src/fake/console/mod.rs
- unittest/src/fake/console/tests.rs
- unittest/src/fake/mod.rs
This is an implementation of the interface to the console driver.
It implements printing only, and the Write trait.
I'm not entirely sure about the Config traits for Allow and Subscribe.
I'm also not sure if the tests are structured correctly – e.g. integration testing would have to basically reimplement the same code as is already in the `write` API call, so I skipped that (but perhaps that's the point).
There's also a "hello world" example, so it would check off a few boxes from https://github.com/tock/libtock-rs/issues/322
> Add console driver API

- Cargo.toml
- Makefile
- libtock2/Cargo.toml
- libtock2/src/lib.rs
- panic_handlers/debug_panic/Cargo.toml
- panic_handlers/debug_panic/src/lib.rs
This adds a panic handler printing panic information to the console if possible.
If not possible, it signals failure using the low level mechanism.
The console handler becomes the default.
Follows up on https://github.com/tock/libtock-rs/pull/395
> Use console panic handler

- Makefile
- runner/src/elf2tab.rs
- runner/src/main.rs
This PR changes the runner to provide the architecture of elf files to elf2tab. It requires https://github.com/tock/elf2tab/pull/38.
> Provide elf architecture to elf2tab

- runner/src/output_processor.rs
Previously, if the Tock system printed a message that did not end with an EOL character, that message would not immediately appear on the terminal. This can be somewhat confusing. With this change, each message output by the Tock system appears on the terminal immeditately.
> Runner: flush stdout after each echo.

- apis/console/src/lib.rs
- apis/console/src/tests.rs
- unittest/src/fake/console/mod.rs
- unittest/src/fake/console/tests.rs
Reading limited to bytes. Reading strings makes some sense in a human context, but there is no API for waiting on a character, so it was skipped.
I think I might have a bug somewhere in tests when handling errors because the buffer should have been filled. Or maybe I just don't understand the test framework.
> Add console read

- apis/console/src/lib.rs
Currently, `apis/console/src/lib.rs` only contains `platform::allow_ro::Config + platform::allow_rw::Config + platform::subscribe::Config` twice. However, when I introduce the async APIs, I will be duplicating that trait bound several times. This PR makes an alias for that combination of traits, to avoid code duplication when I introduce async APIs.
> Console: create a `Config` trait that aliases the Allow RO/Allow RW/Subscribe config traits.

- apis/buttons/src/lib.rs
- apis/gpio/src/lib.rs
- platform/src/share/tests.rs
- platform/src/syscalls_impl.rs
- runner/src/main.rs
- rust-toolchain
- unittest/src/allow_db.rs
- unittest/src/exit_test/mod.rs
- unittest/src/fake/buttons/mod.rs
- unittest/src/fake/gpio/mod.rs
- unittest/src/fake/low_level_debug/mod.rs
- unittest/src/fake/syscalls/subscribe_impl.rs
- unittest/src/syscall_log.rs
- unittest/src/upcall.rs
This contains 3 categories of changes to avoid warnings and failures:
1. `clippy` now warns if you derive `PartialEq` without also deriving `Eq`. All of the types that triggered this warning can implement `Eq`, so I added `Eq` derives.
2. Miri no longer allows integer-to-function-pointer casts. I tweaked the subscribe implementations to avoid casting through `usize`.
3. `clippy` added a warning for expressions of the form `let var: () = expr();`, but we did that intentionally as part of a compile test. I disabled that warning for the relevant test case.
> Update the nightly toolchain to 2022-06-10.

- Makefile
This merges the two miri commands together, as strict provenance is strictly more restrictive than all other configurations.
See https://github.com/rust-lang/miri/pull/2045 for some more background on `-Zmiri-strict-provenance`.
Closes #400
> Enable strict provenance in Miri.

- .ignore
`ripgrep` skips hidden directories by default. This overrides that, and tells it to include `.cargo/` and `.github/` in its search path.
> Tell search tools to search the `.cargo` and `.github` directories.

- runner/Cargo.toml
This fixes builds which have a Cargo.lock with clap <3.2.
> runner: Adjust clap version to match used features

- doc/FaultDebuggingExample.md
This is the debugging example from issue #362, but with a more permanent home in the `doc/` directory.
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/debugging-example/doc/FaultDebuggingExample.md)
> Add a process fault debugging example to `doc/`.

- .github/workflows/ci.yml
GitHub Actions' environments now contain a sufficiently-new stable toolchain for `libtock-rs`. Remove the toolchain update step, as it is now a waste of time.
> Remove `rustup toolchain update stable` from CI, it is no longer needed.

- Makefile
As of version `0.5.0`, `stack-sizes` is [no longer a binary crate](https://github.com/japaric/stack-sizes/pull/14). This breaks our CI, which tries to install the latest version of the `stack-sizes` binary.
This PR removes all references to the tool from `libtock-rs`, so that CI can continue working.
`stack-sizes` appears to have been replaced by [`cargo-call-stack`](https://github.com/japaric/cargo-call-stack), which we may add support for in the future.
> Remove our use of the `stack-sizes` tool.

- .cargo/config
- apis/alarm/src/lib.rs
- apis/console/src/lib.rs
- platform/src/command_return.rs
- platform/src/register.rs
- unittest/src/share_data.rs
- unittest/src/upcall.rs
**This PR is a request for comments, please see below**
The [`unused-qualifications`](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unused-qualifications) lint is included in rustc, but disabled by default. This enables the lint, and fixes locations that trigger it.
However, I'm not sure that all of the changes I made were an improvement. Several of our tests contained the following pattern:
```rust
let called = Cell::new(Option::<(u32,)>::None);
```
This pattern triggers the lint, indicating the `Option::<(u32,)>::` is optional. In other words, we can write:
```rust
let called = Cell::new(None);
```
and Rust will infer the `Option`'s generic parameters. However, the inferred parameters are not obvious, and we intentionally specified the types to help human …
> Apply the unused-qualifications lint.

- apis/alarm/src/lib.rs
closes #446
ran `make test` which concluded with  `[ SUCCESS ] libtock-rs tests pass`
> fixed incorrect inference

- syscalls_tests/src/subscribe_tests.rs
- unittest/src/fake/syscalls/subscribe_impl.rs
- unittest/src/fake/syscalls/subscribe_impl_tests.rs
This updates the Tock submodule to the 2.1.1 release and adjusts the fake kernel's error codes to correspond with the corrections in https://github.com/tock/tock/pull/3300.
> Update to Tock 2.1.1.

- CONTRIBUTING.md
- README.md
- doc/Overview.md
- doc/PlatformDesignStory.md
- doc/Testing.md
Rendered files:
1. [`README.md`](https://github.com/jrvanwhy/libtock-rs/blob/doc-update/README.md)
1. [`CONTRIBUTING.md`](https://github.com/jrvanwhy/libtock-rs/blob/doc-update/CONTRIBUTING.md)
1. [`doc/Overview.md`](https://github.com/jrvanwhy/libtock-rs/blob/doc-update/doc/Overview.md)
1. [`doc/PlatformDesignStory.md`](https://github.com/jrvanwhy/libtock-rs/blob/doc-update/doc/PlatformDesignStory.md)
1. [`doc/Testing.md`](https://github.com/jrvanwhy/libtock-rs/blob/doc-update/doc/Testing.md)
This PR does not update `CHANGELOG.md`.
> Update the docs for the Tock 2.0 version of `libtock-rs`.

- Makefile
- runner/src/elf2tab.rs
- runtime/layouts/raspberry_pi_pico.ld
This pull request fixes the Raspberry Pi Pico's board name and layout.
This was tested using a Raspberry Pi Pico.
It would be great if we could merge this until the Rust Nation presentation.
> Fix Raspberry Pi Pico board and layout

- .github/workflows/artifacts.yml
- Makefile
- runner/src/tockloader.rs
This PR adds Imix to the github workflows, Makefile, and runner. The layout file and other support had already been added previously. Tested by running blink on an Imix using make flash-imix EXAMPLE=leds
> Finish adding imix support for libtock-rs

- .github/workflows/mac-os.yml
There is an issue with the macos runner in the CI because ```macos-10.15``` has been deprecated an now it takes a day until the check gets timeout.
I suggest using ```macos-latest``` in order to have always the latest LTS runner in the CI
> Update macos-10.15 to macos-latest

- runtime/libtock_layout.ld
Rust's default linker (llvm-ld) as used with the Rust toolchain versions of at least `2022-06-10`, `2023-01-26`, and `2023-06-27` can produce broken ELF binaries when the RAM region's start address is not well-aligned to a 4kB boundary. Unfortunately, this behavior is rather tricky to debug: instead of refusing to produce a binary or producing a corrupt output, it generates an ELF file which includes a segment that points to the ELF file's header itself. elf2tab will include this segment in the final binary (as it is set to be loaded), producing broken TBFs. This (overrideable) check is designed to warn users that the linker may be misbehaved under these conditions.
To reproduce this on this current git revision, with a Rust toolchain version `2023-06-27`, change the `opentitan.ld` layout …
> runtime/libtock_layout.ld: ASSERT well-aligned RAM address

- runtime/libtock_layout.ld
This change ensures that no ELF-segment will have a `PhysAddr` which points outside of the `FLASH` memory region. This is important for ROM-loaders such as elf2tab to reliably produce correct binaries.
Previously, `.stack` and `.bss` sections were simply instructed to be placed into RAM. Without an explicitly specified load address or load address region, this means that their ELF-segment's `PhysAddr` will be set to its `VirtAddr` (and hence point into RAM):
Program Headers:
Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
LOAD           0x001000 0x20030000 0x20030000 0x00000 0x00060 R   0x1000
LOAD           0x001060 0x20030060 0x20030060 0x00d64 0x00d64 R E 0x1000
LOAD           0x001dc4 0x20030dc4 0x20030dc4 0x001ec 0x001ec R   0x1000
LOAD           0x002000 …
> runtime/libtock_layout.ld: use FLASH-segment LMAs for all sections

- unittest/src/fake/kernel.rs
Add helper functions to fake Kernel that allow unit test to make better decision about code flow.
We have used both of these functions downstream in our unit tests.
> Add helper function to fake Kernel

- Makefile
This should fix our CI, until we can ship a proper Rust toolchain update (#481).
> Makefile: use stable rustc to install elf2tab

- examples/blink.rs
Works the same as the libtock-c version.
> Add the classic blink app

- platform/src/subscribe.rs
One convention in Tock is that the first argument of an upcall is a return code. A return code is an `ErrorCode` but 0 means Success.
This makes it possible to write a subscribe callback like:
```rust
let called: Cell<Option<Result<(), ErrorCode>>> = Cell::new(None);
let called: Cell<Option<Result<(u32,), ErrorCode>>> = Cell::new(None);
let called: Cell<Option<Result<(u32, u32), ErrorCode>>> = Cell::new(None);
```
My implementation of converting a u32 to an errorcode is functional but not great, any ideas on what that should look like?
> platform: subscribe: add return code variants

- examples/buttons.rs
Seems like maybe this wasn't updated at some point?
I did need to make the stack bigger.
> examples: buttons: fix

- apis/adc/src/lib.rs
- unittest/src/fake/adc/mod.rs
- unittest/src/fake/adc/tests.rs
This is a bug in the kernel which will be fixed in future releases but for now we enable the ADC example to work.
> api: adc: exists needs to handle number of channels

- doc/Style.md
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/naming-convention-doc/doc/Style.md)
Currently, the only contents of the style guide is a naming convention guide that describes when to use the `libtock_` prefix. I suspect it will grow beyond that in the future.
> Add a style guide.

- .github/workflows/artifacts.yml
- .github/workflows/ci.yml
- .github/workflows/mac-os.yml
- .github/workflows/size-diff.yml
Similarly to https://github.com/tock/tock/pull/3591, this PR updates the versions of dependencies used in GitHub Actions to avoid the removal of Node v12 on Monday.
Two of the workflows are fixed on `ubuntu-20.04` for stability, although I think GitHub will also remove Node v12 from these runners too. There's no harm in updating them either way if they still work.
> Update GitHub Actions

- Makefile
Not all systems have a /bin/bash (e.g., NixOS). Using either /usr/bin/env to look for an appropriate shell binary in the PATH, or using /bin/sh directly is more reliable and portable.
Fixes #504.
> Makefile: use /usr/bin/env bash in favor of /bin/bash

- apis/adc/src/lib.rs
- apis/air_quality/src/lib.rs
- apis/ambient_light/src/lib.rs
- apis/buzzer/src/lib.rs
- apis/ninedof/src/lib.rs
- apis/proximity/src/lib.rs
- apis/sound_pressure/src/lib.rs
- apis/temperature/src/lib.rs
- platform/src/error_code_tests.rs
- unittest/src/fake/air_quality/mod.rs
- unittest/src/fake/ambient_light/mod.rs
- unittest/src/fake/gpio/mod.rs
- unittest/src/fake/sound_pressure/mod.rs
I'm preparing a toolchain update PR that will supercede #481. I'd prefer to avoid sending a large PR that mixes these style updates with important `unsafe` code, so I'm splitting the update into two PRs.
> Apply fixes suggested by Clippy version `nightly-2023-08-22`.

- platform/src/register.rs
- rust-toolchain
- unittest/Cargo.toml
The semantics of int-to-pointer casts under strict provenance has changed. Ideally, we would update our `From<usize> for Register` implementation to use the `sptr` crate, but `sptr` does not currently have a suitable license. There is a [PR](https://github.com/Gankra/sptr/pull/14) to change that, but it hasn't gotten a response in 7 months, so I don't think we can use it. Instead, this copies the implementation of `core::ptr::invalid`.
This also bumps our `thiserror` dependency, which forces Cargo to pick a newer version of `proc-macro2` that is compatible with recently nightly toolchains.
> Update the Rust toolchain to `nightly-2023-08-22`.

- build_scripts/src/lib.rs
Without setting this, lld seems to assume 0x10000 sized pages and tries to align the output segments to 0x10000. This often causes elfs with large padding regions before the first segment we actually want to load on the board.
See https://github.com/tock/elf2tab/pull/75 for further discussion.
> build/make: set the page size

- Cargo.toml
- doc/Style.md
I've been keeping a lot of things (such as `Cargo.toml` package lists and `mod` declarations) in alphabetical order. This adds that preference to the style guide.
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/style-list-order/doc/Style.md)
> Coding style: add a section on list ordering.

- build_scripts/libtock_layout.ld
This PR is on top of the make updates because that lets me test it. We only care about the latest commit: https://github.com/tock/libtock-rs/commit/79e25cf6f878a695a5b8dd9e32a479b6f3848fbc
The llvm linker seems to make sure the first segment is aligned to a flash page, and assumes the page size is 0x10000. This causes elfs with a segment before what we set as the start of flash:
```
readelf.py -lS target/cortex-m4.0x00048000.0x1000a000/console
There are 22 section headers, starting at offset 0x26f1c
Section Headers:
[Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
[ 0]                   NULL            00000000 000000 000000 00      0   0  0
[ 1] .start            PROGBITS        00048080 008080 000074 00  AX  0   0  1
[ 2] .text             PROGBITS …
```
> ld: Check for alignment between FLASH_START and linker page size

- .gitignore
- Cargo.toml
- Makefile
- nightly/rust-toolchain.toml
- rust-toolchain
- rust-toolchain.toml
This PR defines a Minimum Supported Rust Version. It specifies that toolchain in `rust-toolchain`, so `rustup` will use that toolchain by default. The `test-stable` make action is removed, as it is now redundant.
We still need the nightly toolchain for Miri. Instead of specifying the nightly toolchain version via the command line, I created a new `nightly/rust-toolchain.toml` file that specifies the toolchain. The benefit is this makes `rustup` automatically install the nightly toolchain *including Miri*. This should stop the toil we currently have where every time the Rust toolchain is updated, everyone using `make test` has to manually install new toolchains and Miri. The downside is the directory change we need to use it is kinda ugly.
I set the MSRV to 1.70 so this doesn't conflict …
> Define a MSRV, use that toolchain by default.

- Makefile
Right now the non cortex-m3+ platforms don't build correctly.
> make: specify target with each platform

- apis/gpio/src/lib.rs
- examples/gpio.rs
Simple GPIO interrupt example. Tested on the nRF52840dk.
> Add GPIO example

- Makefile
- nightly/rust-toolchain.toml
This PR fixes two race conditions in `libtock-rs`' Makefile:
1. Running e.g. `make -j2 hail flash-hail EXAMPLE=console` will cause concurrent `cargo run` invocations that race (another variant of [#366](https://github.com/tock/libtock-rs/issues/366)). This was fixed by changing the target directories for the `flash-*` targets.
2. Running `make -j2 test` with a missing toolchain can result in parallel toolchain installs, which corrupts the toolchain.
I also fixed `make clean`, which wasn't cleaning up the nightly toolchain's target directory.
> Fix Makefile race conditions.

- apis/adc/src/lib.rs
- apis/adc/src/tests.rs
- apis/air_quality/src/tests.rs
- apis/alarm/src/lib.rs
- apis/ambient_light/src/tests.rs
- apis/buzzer/src/tests.rs
- apis/console/src/lib.rs
- apis/console/src/tests.rs
- apis/gpio/src/lib.rs
- apis/leds/src/tests.rs
- apis/low_level_debug/src/lib.rs
- apis/low_level_debug/src/tests.rs
- apis/ninedof/src/tests.rs
- apis/proximity/src/tests.rs
- apis/sound_pressure/src/tests.rs
- apis/temperature/src/tests.rs
- unittest/src/fake/alarm/mod.rs
- unittest/src/fake/console/mod.rs
- unittest/src/fake/console/tests.rs
- unittest/src/fake/gpio/mod.rs
- unittest/src/fake/leds/mod.rs
- unittest/src/fake/leds/tests.rs
- unittest/src/fake/low_level_debug/mod.rs
- unittest/src/fake/low_level_debug/tests.rs
Bring libtock-rs into consistency with the changes in [this PR](https://github.com/tock/tock/pull/3613/).
Only `apis/gpio/src/lib.rs` needed to be changed. The rest is a grepped driver_check -> exists.
> apis: update breaking driver existence check changes

- Cargo.toml
- apis/i2c_master_slave/Cargo.toml
- apis/i2c_master_slave/src/lib.rs
- examples/i2c_master_write_read.rs
- examples/i2c_slave_send_recv.rs
- src/lib.rs
Adds new I2C master/slave api to libtock-rs. The changes were tested using the samples running on 2x Particle Boron boards. Where one was a master and the other was a slave device, that would ping-pong data across. Additional testing was performed by communicating with an MCP9808 device as an I2C bus Master.
The samples can be built by running the below from the top-dir:
```
$ make nrf52840 EXAMPLE=i2c_slave_send_recv
$ make nrf52840 EXAMPLE=i2c_master_write_read
```
After flashing each sample to the respective master and slave device. The following serial output can be observed. Note you may have to reset the devices after flashing.
```
i2c-master: write-read operation 1
2 bytes read from slave | data received (0h): [c1, c5]
i2c-master: write-read operation 2
2 bytes read from slave | …
```
> api: add i2c master/slave support | examples: add i2c master/slave samples

- examples/usb_i2c_mctp.rs
Add a sample libtock-rs app that allows a host machine without exposed I2C/SMBus capabilities to communicate to an MCTP endpoint.
The following topology is used:
```
[Host PC] <-- UART --> [Usb-I2C Bridge Device] <-- I2C --> [Target Endpoint]
```
This app operates by first waiting for an MCTP request packet to be sent over UART from the host, which is then forwarded to the target endpoint (based on the target address) through the I2C bus. The endpoint must then master the I2C bus and write a response back to us, as we wait in target mode (Note: MCTP mandates writes only).  This is then forwarded to the host machine via UART.
A sample use-case  can be to communicate with an SPDM responder that uses  MCTP/SMBus/I2C, directly from the host machine.
The host app must attach a small packet …
> examples: add usb-i2c mctp app

- Cargo.toml
- rust-toolchain.toml
We are starting to see failures with our current version of Rust [1] when building elf2tab.
We could look at pinning an older elf2tab, but that brings with it a range of issues. Instead let's bump our MSRV to a newer stable.
1: https://github.com/tock/libtock-rs/pull/533#issuecomment-1944945234
> Bump the Rust MSRV

- Cargo.toml
- apis/i2c_master/Cargo.toml
- apis/i2c_master/src/lib.rs
- apis/i2c_master_slave/src/lib.rs
- src/lib.rs
Extend the existing i2c_master_slave API to support the exists command and then add support for the i2c_master syscall interface
> I2C: Support i2c_master_slave exists and initial support for i2c_master syscalls

- build_scripts/src/lib.rs
Hi!
I'm really sorry, last pull request: #537  was not completed as there is a little portion of RAM already in use.
Ram layout for applications in Arduino Nano33ble starts in 0x20005000
Now, the first application compiles and can be loadable in a nano33ble board.
Cheers
> fixed RAM memory layout for nano33ble

- Cargo.toml
- README.md
- apis/gpio/Cargo.toml
- apis/gpio/src/lib.rs
- platform/Cargo.toml
- platform/src/error_code.rs
This is very initial support for the embedded_hal [1]. This allows general embedded Rust crates to be built on top of libtock-rs with minimal porting effort.
This currently just stubs out the support and implements the `digital::OutputPin` trait for GPIO pins.
1: https://docs.rs/embedded-hal/1.0.0/embedded_hal/index.html
> Initial support for the Rust Embedded embedded-hal

- Cargo.toml
- nightly/rust-toolchain.toml
- rust-toolchain.toml
When trying to build embedded-hal-async we get this error
error: package `embedded-hal-async v1.0.0` cannot be built because
it requires rustc 1.75 or newer, while the currently active rustc
version is 1.74.1
So let's upgrade to 1.75 to allow us to build embedded-hal-async.
> Bump Rust to version 1.75

- Cargo.toml
- apis/spi_controller/Cargo.toml
- apis/spi_controller/src/lib.rs
- examples/spi_controller_write_read.rs
- platform/src/error_code.rs
- src/lib.rs
- src/spi_controller.rs
This includes initial support for the spi_controller api, including
embedded-hal support. This also sets up a spi_controller_write_read
example for testing.
This applies on top of https://github.com/tock/libtock-rs/pull/540
> spi_controller: Initial support

- doc/Overview.md
We could try to add all of the drivers to the table, but that will probably never stay up-to-date, so perhaps it's better to just remove the table and point readers in the right direction.
I don't feel strongly about this, perhaps it's better for someone to write a script to populate this table.
> doc: overview: remove outdated list

- build_scripts/src/lib.rs
Works with https://github.com/tock/tock/pull/4030
> build_scripts: Allow us to use all of the flash allocated by the kernel

- Cargo.toml
- Makefile
- build_scripts/libtock_layout.ld
- demos/st7789-slint/Cargo.toml
- demos/st7789-slint/build.rs
- demos/st7789-slint/src/main.rs
- demos/st7789-slint/ui/appwindow.slint
Demo application using [Slint](https://slint.dev/) and midipi to display a GUI on a `st7789`
Depends on https://github.com/tock/libtock-rs/pull/549 otherwise the build fails as we run out of flash
> demos: Add support for a Slint demo

- .cargo/config
- Cargo.toml
Very simply add three Cargo flags by default that seem to have a reasonable impact on code size in many examples, all used in the kernel as well:
1. `opt-level = "z"` is LLVM's `-Os`, i.e., optimize for size not speed, please. This seems to help in all but very small examples (under 1k)
2. `codegen-units = 1` restricts Cargo from splitting crates up during compilation and in general should improve LTO the cost is slower compile times. In practice, this doesn't seem to make a difference in this repo for now, so this is mostly a forward thinking precaution.
3. `"-C link-arg=-icf=all" combines identical compiled procedures. Seems to have marginal benefit.
> Simple size optimization flags for Cargo by default

- Cargo.toml
- src/lib.rs
`panic_handler/small_panic` is significantly smaller than the current default `panic_handler/debug_panic` since it doesn't bother formatting a panic message, instead using the low-level-debugger and exiting.
However, it's not actually used anywhere (maybe downstream?)!
This PR uses `small_panic` in release mode and `debug_panic` in debug mode. There is a pretty substantial drop in code size for most examples.
> Enable `small_panic` in release mode

- platform/src/register.rs
- platform/src/syscalls.rs
- platform/src/syscalls_impl.rs
- runtime/src/startup/mod.rs
- syscalls_tests/src/lib.rs
- syscalls_tests/src/memop_tests.rs
- unittest/src/expected_syscall.rs
- unittest/src/fake/kernel.rs
- unittest/src/fake/syscalls/memop_impl.rs
- unittest/src/fake/syscalls/memop_impl_tests.rs
- unittest/src/fake/syscalls/mod.rs
- unittest/src/fake/syscalls/raw_syscalls_impl.rs
- unittest/src/fake/syscalls/raw_syscalls_impl_tests.rs
- unittest/src/kernel_data.rs
- unittest/src/syscall_log.rs
This PR adds memop syscalls corresponding to memop 0, 1, 2, 10, and 11 to libtock-rs. Any instances where the underlying raw system calls were being used to call memop are migrated to the safe higher level syscall APIs as possible. This PR also adds a function to libtock-runtime for retrieving the value of _heap_start as set by the linker.
This PR also builds out some initial infrastructure for unit tests to include the memop syscall, and some tests of the system call implementation itself. This was definitely the trickier part of this PR. Because many of these memop APIs need to accept pointers for argument0, and because the unit tests include Miri's strict provenance tests, I modified the expected syscall type and the syscall log type to use the "Register" type for memop argument0, …
> Initial memop syscall implementation + tests

- Cargo.toml
- doc/PlatformDesignStory.md
- platform/src/share/tests.rs
- rust-toolchain.toml
- syscalls_tests/src/allow_ro.rs
- syscalls_tests/src/allow_rw.rs
- syscalls_tests/src/subscribe_tests.rs
- unittest/src/kernel_data.rs
When trying to build rowan we get this error
error: package `rowan v0.15.16` cannot be built because
it requires rustc 1.77.0 or newer, while the currently active rustc
version is 1.75.0
So let's upgrade to 1.77 to allow us to build rowan.
> Bump Rust to version 1.77

- apis/interface/buttons/src/lib.rs
- apis/interface/console/src/lib.rs
- apis/interface/leds/src/lib.rs
- apis/kernel/low_level_debug/src/lib.rs
- apis/peripherals/alarm/src/lib.rs
- apis/peripherals/gpio/src/lib.rs
- unittest/src/fake/alarm/mod.rs
- unittest/src/fake/buttons/mod.rs
- unittest/src/fake/console/mod.rs
- unittest/src/fake/gpio/mod.rs
- unittest/src/fake/leds/mod.rs
- unittest/src/fake/low_level_debug/mod.rs
This pull request corrects the driver ID naming. Previously, driver IDs were inconsistently represented using a mix of decimal and hexadecimal formats, leading to potential confusion and errors.
Changes:
- Replaced all occurrences of driver IDs with their hexadecimal equivalents.
> Fix Driver ID Naming to Hexadecimal Format

- platform/src/register.rs
Now that the presence of provenance in Rust has been stabilized, we should document the effect that `Register` has on pointer provenance. Note that the current implementation sometimes attaches provenance when we don't want it to, which we can only fix when strict provenance is stabilized (which should happen in Rust 1.84).
This also fixes the implementation of `From<usize> for Register`, which relies on transmuting a usize to a pointer, which [is not a stable guarantee](https://github.com/rust-lang/rust/blob/81eef2d362a6f03db6f8928f82d94298d31eb81b/library/core/src/ptr/mod.rs#L640), and makes a few other style improvements.
> Register: document provenance, fix conversion implementations.

- Makefile
- rust-toolchain.toml
This pull request adds support for the Cortex-M33 architecture.
I tested this on a Raspberry Pi Pico 2.
> Add support for Cortex-M33

- runtime/src/syscalls_impl_arm.rs
`asm_const` feature has been stabilized in Rust 1.82. Using const operands for inline assembly eliminates a lot of the duplicated code in the ARM syscall implementation.
This commit has been tested by running a simple application that periodically blinks and writes a message on Raspberry Pi Pico.
> Use const operand for ARM syscall implementation

- .github/workflows/ci.yml
- .gitignore
- Cargo.toml
- Makefile
- demos/embedded_graphics/buttons/Cargo.toml
- demos/embedded_graphics/buttons/Makefile
- demos/embedded_graphics/buttons/README.md
- demos/embedded_graphics/buttons/build.rs
- demos/embedded_graphics/buttons/src/main.rs
- demos/embedded_graphics/spin/Cargo.toml
- demos/embedded_graphics/spin/Makefile
- demos/embedded_graphics/spin/README.md
- demos/embedded_graphics/spin/build.rs
- demos/embedded_graphics/spin/src/main.rs
- libraries/embedded_graphics_libtock/Cargo.toml
- libraries/embedded_graphics_libtock/README.md
- libraries/embedded_graphics_libtock/src/lib.rs
- libraries/embedded_graphics_libtock/src/tock_screen.rs
This uses #568.
It provides basic support for using the embedded graphics library with the Tock screen syscall.
I was able to port the spin demo from libtock-c and verify that it works on the nrf52840dk with the attached monochromatic screen.
> Support Embedded Graphics using the `screen` system call

- apis/display/screen/src/lib.rs
- unittest/src/fake/screen/mod.rs
- unittest/src/fake/screen/tests.rs
Right now the screen driver calls yield no matter what command returns. However, if a command returns an error no upcall will be called. This checks the return from the command and only calls yield if command returned success.
> api: screen: return if command fails
