tock/libtock-rs

README.md
There's some invisible steps for the not deeply in-the-know
=> Add basic build directions

src/led.rs
I just learned about the Tock project and I am extremely excited about the idea of developing my own programs for it, as well as contributing to the project itself. I hope this small PR can be a small step towards becoming a productive contributor to the project. I have a great passion for beautiful, concise, and clean code.
It might make sense to prefix these constants; let me know if you'd prefer that.
=> Using u32 constants for LED instructions

src/led.rs, src/timer.rs
- fix the driver numbers according the documentation
- change the interface for delay_ms to take a relative time
=> Driver fixes

.vscode/settings.json
This PR updates
- Xargo, including japaric/xargo#201
- Tock
- Rust toolchain used by RLS
=> Update dependencies/Fix dirty Cargo.lock in xargo folder

src/entry_point.rs
This should do all necessary initialization except for dynamic relocations. We do not perform dynamic relocations yet because it's unclear what they will look like for ROPI-RWPI.
=> Initialize .data and .bss in libtock-rs.

src/timer.rs
- Make `Duration` a generic type, supporting both `isize` and `f64` representation.
- Derive comparison traits for `Duration`.
- Add a `Timestamp` type and arithmetic between `Duration`s and `Timestamp`s.
=> Enhance the timer interface.

src/timer.rs
To avoid overflow errors for large clock rates let's divide the time
before we multiply it.
Fixes: https://github.com/tock/libtock-rs/issues/51
=> timer: Fixup alarm tick calculation

examples/hello_world.rs
Add a really small "Hello World" example. This is useful for testing
libtock-rs on the HiFive1 as the app is small, simple and easy to debug.
=> examples: Add a hello_world

Makefile
=> Makefile: Fix the OpenTitan target

Makefile
=> Makefile: Fix the release and feature flag options

README.md
I initially misunderstood the README directions and thought that simply running
```make hail``` would build all examples in this repo and flash them to my device.
(#175 )
Although it was on part my bad for misunderstanding the README , 
I made a small update to make the directions a bit more clear.
Please feel free to close this PR if you feel this change is unnecessary.
Thank you for reviewing this PR :+1:
=> small update to instructions in README

examples/hmac.rs, src/drivers.rs, src/hmac.rs, src/lib.rs
This PR adds the HMAC driver and a HMAC example.
=> Add support for running HMAC operations

Makefile, boards/layout_apollo3.ld, tools/flash.sh
Signed-off-by: Alistair Francis <alistair@alistair23.me>
=> boards: Add support for the apollo3

Makefile
Signed-off-by: Alistair Francis <alistair@alistair23.me>
=> Makefile: Correctly document the Apollo3 support

tools/flash.sh
Fixes #182.
---
Yes, there are more elaborate fixes available, but this is an easy case where perfect is the enemy of good. Let's unblock mac users.
=> replace `readlink`

README.md
=> README: Update to better describe Tock kernel version support

examples/hello_world.rs
This PR adds a one helping comment to the example program **examples/hello_world.rs**.
The comment tells where to look to see the "Hello World" message printed out.
I thought adding this line would be helpful to newcomers like me :smile_cat: 
p.s. 
Is running `tockloader listen` the canonical way to view messages printed to the console?
Thank you for reviewing this PR :) :cake:
=> add comment on where to look to view 'Hello World' message

Cargo.toml
=> Cargo.toml: Bump the serde crate

boards/layout_opentitan.ld
=> boards/layout_opentitan.ld: Update memory addresses

examples/hmac.rs, src/hmac.rs
=> hmac: Implement Deref and DerefMut for the HMAC buffers

Makefile
Fixes #249
Signed-off-by: Tobias Wölfel <tobias.woelfel@mailbox.org>
=> elf2tab: Update to current version

src/drivers.rs, src/i2c.rs, src/lib.rs
=> i2c: Add support for the I2C interface

examples/ninedof.rs
=> Add ninedof example

Makefile, boards/layout_stm32f3discovery.ld
Adds support for stm32f3discovery.
=> stm32f3discovery support

examples-features/ctap.rs
=> examples-features/ctap: Ensure the stack is created

core/src/result.rs
Adding the remaining ReturnCode values that exist in [tock/returncode.rs](https://github.com/tock/tock/blob/master/kernel/src/returncode.rs)
=> Update result.rs with remaining ReturnCode values

unittest/src/fake/low_level_debug/mod.rs, unittest/src/fake/low_level_debug/tests.rs, unittest/src/fake/mod.rs
This is the first proper `fake::Driver` implementation!
=> Implement a fake LowLevelDebug API.

platform/src/error_code.rs, platform/src/error_code_tests.rs
This also adds a link to the TRD 104 error code page to make the restrictions a bit more clear.
=> Add a TryFrom<u32> impl for ErrorCode

Makefile, runner/src/tockloader.rs, runtime/layouts/clue_nrf52840.ld
This PR adds the CLUE nRF52840 layout and makefile targets.
=> Add CLUE nRF52840

doc/UsingNoAutoLayout.md
[Rendered](https://github.com/jrvanwhy/libtock-rs/blob/no-auto-layout-doc/doc/UsingNoAutoLayout.md)
Closes #354.
=> Add a document describing how to use `no_auto_layout`.

examples/buttons.rs, src/lib.rs
This pull requests add several data structure exports. This was not a problem as all the examples are in the crate, but it becomes a problem when this is used as a library.
It would be great if we can merge this before the Rust Nation presentation.
=> Fix the API

Makefile
=> Specify Bash as the shell to use in Makefile.
